// <auto-generated />
using System;
using DriveOS.Modules.ExamsCertification.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveOS.Modules.ExamsCertification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExamsCertificationDbContext))]
    [Migration("20260821183619_AddExamPlaceWatcher")]
    partial class AddExamPlaceWatcher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exams_certification")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Places.ExamCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<string>("AdministrativeAreaCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("administrative_area_code");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ExternalCenterId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_center_id");

                    b.Property<string>("ExternalProviderCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_provider_code");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CountryCode", "Name")
                        .HasDatabaseName("ix_exam_center_org_country_name");

                    b.HasIndex("OrganizationId", "ExternalProviderCode", "ExternalCenterId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_center_external")
                        .HasFilter("external_provider_code IS NOT NULL AND external_center_id IS NOT NULL");

                    b.ToTable("exam_centers", "exams_certification");
                });

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Places.ExamPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_student_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<Guid>("ExamCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_center_id");

                    b.Property<Guid?>("ExamRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_registration_id");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("exam_type");

                    b.Property<string>("ExternalPlaceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_place_id");

                    b.Property<Guid?>("HeldByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("held_by_user_id");

                    b.Property<DateTimeOffset?>("HoldExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at_utc");

                    b.Property<Guid?>("HoldToken")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_token");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("license_category");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProviderCode", "ExternalPlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_place_external")
                        .HasFilter("external_place_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "StartsAtUtc", "Status")
                        .HasDatabaseName("ix_exam_place_calendar");

                    b.HasIndex("OrganizationId", "ExamCenterId", "StartsAtUtc", "LicenseCategory")
                        .HasDatabaseName("ix_exam_place_center_slot");

                    b.ToTable("exam_places", "exams_certification");
                });

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Places.Watch.ExamPlaceWatchHit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_place_id");

                    b.Property<DateTimeOffset>("FirstDetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FirstDetectedAtUtc")
                        .HasDatabaseName("ix_exam_place_watch_hit_detected");

                    b.HasIndex("SubscriptionId", "ExamPlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_place_watch_hit_once");

                    b.ToTable("exam_place_watch_hits", "exams_certification");
                });

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Places.Watch.ExamPlaceWatchScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<int>("ExternalSlotsRead")
                        .HasColumnType("integer")
                        .HasColumnName("external_slots_read");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int>("NewAvailabilitiesDetected")
                        .HasColumnType("integer")
                        .HasColumnName("new_availabilities_detected");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "SubscriptionId", "StartedAtUtc")
                        .HasDatabaseName("ix_exam_place_watch_scan_history");

                    b.ToTable("exam_place_watch_scans", "exams_certification");
                });

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Places.Watch.ExamPlaceWatchSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrativeAreaCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("administrative_area_code");

                    b.Property<string>("CenterExternalIds")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("center_external_ids");

                    b.Property<int>("CheckIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("check_interval_minutes");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failure_count");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ExamCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exam_category");

                    b.Property<DateTimeOffset?>("LastAvailabilityDetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_availability_detected_at_utc");

                    b.Property<DateTimeOffset?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<DateTimeOffset?>("LastSuccessfulCheckAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_check_at_utc");

                    b.Property<DateTimeOffset>("NextCheckAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_check_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProcessingLeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_lease_token");

                    b.Property<DateTimeOffset?>("ProcessingLeaseUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_lease_until_utc");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("WindowFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_from_utc");

                    b.Property<DateTimeOffset>("WindowToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_to_utc");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProviderCode")
                        .HasDatabaseName("ix_exam_place_watch_provider");

                    b.HasIndex("Status", "NextCheckAtUtc")
                        .HasDatabaseName("ix_exam_place_watch_due");

                    b.ToTable("exam_place_watch_subscriptions", "exams_certification");
                });

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Readiness.ExamReadinessDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrativeCheck")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("administrative_check");

                    b.Property<string>("Conditions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("FinancialCheck")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("financial_check");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("outcome");

                    b.Property<string>("PedagogicalCheck")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pedagogical_check");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("rationale");

                    b.Property<string>("RegulatoryCheck")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("regulatory_check");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at_utc");

                    b.Property<Guid?>("SupersededByDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_decision_id");

                    b.Property<Guid>("TrainingPathId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_path_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "StudentId", "TrainingPathId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_readiness_current")
                        .HasFilter("is_current = TRUE");

                    b.HasIndex("OrganizationId", "StudentId", "TrainingPathId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_readiness_decision_version");

                    b.ToTable("exam_readiness_decisions", "exams_certification");
                });

            modelBuilder.Entity("DriveOS.Modules.ExamsCertification.Domain.Readiness.Opinions.ExamReadinessOpinion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comment");

                    b.Property<string>("Conditions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("EvaluatedRequiredCompetencies")
                        .HasColumnType("integer")
                        .HasColumnName("evaluated_required_competencies");

                    b.Property<bool>("HasCompletedPedagogicalReview")
                        .HasColumnType("boolean")
                        .HasColumnName("has_completed_pedagogical_review");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LatestPedagogicalDecision")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("latest_pedagogical_decision");

                    b.Property<string>("ObservedAutonomy")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("observed_autonomy");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Opinion")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("opinion");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("PreviousOpinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_opinion_id");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<int>("RequiredCompetencies")
                        .HasColumnType("integer")
                        .HasColumnName("required_competencies");

                    b.Property<string>("ReservationCodesSerialized")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reservation_codes");

                    b.Property<string>("Reservations")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reservations");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("TrainingPathId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_path_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_readiness_opinion_operation");

                    b.HasIndex("OrganizationId", "StudentId", "TrainingPathId", "SubmittedAtUtc")
                        .HasDatabaseName("ix_exam_readiness_opinion_timeline");

                    b.HasIndex("OrganizationId", "StudentId", "TrainingPathId", "AuthorId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_readiness_opinion_author_version");

                    b.ToTable("exam_readiness_opinions", "exams_certification");
                });
#pragma warning restore 612, 618
        }
    }
}
