using DriveOS.Modules.CurriculumPedagogy.Domain.RemediationPlans.Events;using DriveOS.SharedKernel.Auditing;using DriveOS.SharedKernel.Domain;using DriveOS.SharedKernel.Identifiers;using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.CurriculumPedagogy.Domain.RemediationPlans;
public sealed class RemediationPlan:AggregateRoot<RemediationPlanId>,IAuditableEntity
{
 private readonly List<RemediationPlanTarget> _targets=[];private RemediationPlan(){}
 private RemediationPlan(RemediationPlanId id,OrganizationId org,PersonId student,TrainingPathId path,UserId responsible,PedagogicalReviewId? sourceReview,string recommendation,decimal? hours,int? sessions,DateOnly reviewDate,DateTimeOffset created):base(id){OrganizationId=org;StudentId=student;TrainingPathId=path;ResponsibleUserId=responsible;SourcePedagogicalReviewId=sourceReview;Recommendation=recommendation;RecommendedPracticalHours=hours;RecommendedSessions=sessions;ReviewDate=reviewDate;Status=RemediationPlanStatus.Draft;PlanCreatedAtUtc=created.ToUniversalTime();}
 public OrganizationId OrganizationId{get;private set;}public PersonId StudentId{get;private set;}public TrainingPathId TrainingPathId{get;private set;}public UserId ResponsibleUserId{get;private set;}public PedagogicalReviewId? SourcePedagogicalReviewId{get;private set;}public string Recommendation{get;private set;}=string.Empty;public decimal? RecommendedPracticalHours{get;private set;}public int? RecommendedSessions{get;private set;}public DateOnly ReviewDate{get;private set;}public RemediationPlanStatus Status{get;private set;}public DateTimeOffset PlanCreatedAtUtc{get;private set;}public DateTimeOffset? ActivatedAtUtc{get;private set;}public DateTimeOffset? CompletedAtUtc{get;private set;}public DateTimeOffset? CancelledAtUtc{get;private set;}public string? CancellationReason{get;private set;}public IReadOnlyCollection<RemediationPlanTarget> Targets=>_targets.AsReadOnly();public DateTimeOffset CreatedAtUtc{get;private set;}public UserId? CreatedByUserId{get;private set;}public DateTimeOffset? LastModifiedAtUtc{get;private set;}public UserId? LastModifiedByUserId{get;private set;}
 public static Result<RemediationPlan>Create(RemediationPlanId id,OrganizationId org,PersonId student,TrainingPathId path,UserId responsible,PedagogicalReviewId? sourceReview,string recommendation,decimal? hours,int? sessions,DateOnly reviewDate,DateTimeOffset created){if(id.IsEmpty)return Result.Failure<RemediationPlan>(RemediationPlanErrors.InvalidIdentifier);if(org.IsEmpty||student.IsEmpty||path.IsEmpty||responsible.IsEmpty)return Result.Failure<RemediationPlan>(RemediationPlanErrors.InvalidContext);if(string.IsNullOrWhiteSpace(recommendation)||recommendation.Trim().Length>8000)return Result.Failure<RemediationPlan>(RemediationPlanErrors.InvalidRecommendation);if(hours.HasValue&&(hours<=0||hours>1000))return Result.Failure<RemediationPlan>(RemediationPlanErrors.InvalidHours);if(sessions.HasValue&&(sessions<=0||sessions>500))return Result.Failure<RemediationPlan>(RemediationPlanErrors.InvalidSessions);if(reviewDate==default||reviewDate<DateOnly.FromDateTime(created.UtcDateTime.Date))return Result.Failure<RemediationPlan>(RemediationPlanErrors.InvalidReviewDate);var x=new RemediationPlan(id,org,student,path,responsible,sourceReview,recommendation.Trim(),hours,sessions,reviewDate,created);x.RaiseDomainEvent(new RemediationPlanCreatedDomainEvent(x.Id,org,student,path,responsible));return Result.Success(x);}
 public Result AddTarget(RemediationPlanTargetId id,CompetencyId competencyId,string objective){if(Status!=RemediationPlanStatus.Draft||id.IsEmpty||competencyId.IsEmpty||string.IsNullOrWhiteSpace(objective)||objective.Trim().Length>2000)return Result.Failure(RemediationPlanErrors.InvalidTarget);if(_targets.Any(x=>x.CompetencyId==competencyId))return Result.Failure(RemediationPlanErrors.DuplicateTarget);_targets.Add(new RemediationPlanTarget(id,competencyId,objective.Trim()));return Result.Success();}
 public Result Activate(DateTimeOffset at){if(Status!=RemediationPlanStatus.Draft||_targets.Count==0||at==default)return Result.Failure(RemediationPlanErrors.ActivationNotAllowed);Status=RemediationPlanStatus.Active;ActivatedAtUtc=at.ToUniversalTime();RaiseDomainEvent(new RemediationPlanActivatedDomainEvent(Id,TrainingPathId));return Result.Success();}
 public Result Complete(DateTimeOffset at){if(Status!=RemediationPlanStatus.Active||at==default)return Result.Failure(RemediationPlanErrors.CompletionNotAllowed);Status=RemediationPlanStatus.Completed;CompletedAtUtc=at.ToUniversalTime();RaiseDomainEvent(new RemediationPlanCompletedDomainEvent(Id,TrainingPathId,CompletedAtUtc.Value));return Result.Success();}
 public Result Cancel(string reason,DateTimeOffset at){if(Status is RemediationPlanStatus.Completed or RemediationPlanStatus.Cancelled||string.IsNullOrWhiteSpace(reason)||reason.Trim().Length>1000||at==default)return Result.Failure(RemediationPlanErrors.CancellationNotAllowed);Status=RemediationPlanStatus.Cancelled;CancellationReason=reason.Trim();CancelledAtUtc=at.ToUniversalTime();RaiseDomainEvent(new RemediationPlanCancelledDomainEvent(Id,TrainingPathId,CancellationReason));return Result.Success();}
 public void SetCreatedAudit(DateTimeOffset at,UserId? by){if(CreatedAtUtc!=default)return;CreatedAtUtc=at.ToUniversalTime();CreatedByUserId=by;}public void SetModifiedAudit(DateTimeOffset at,UserId? by){LastModifiedAtUtc=at.ToUniversalTime();LastModifiedByUserId=by;}
}
