using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Modules.Organizations.Application.OrganizationSubscriptions.Models;
using DriveOS.SharedKernel.Identifiers;

namespace DriveOS.Modules.Organizations.Application.OrganizationSubscriptions.GetOrganizationSubscription;
public sealed record GetOrganizationSubscriptionQuery(OrganizationId OrganizationId) : IQuery<OrganizationSubscriptionResponse>;
