using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.Workforce.Application.Persistence;
using DriveOS.Modules.Workforce.Domain.Employees;
using DriveOS.Modules.Workforce.Domain.EquipmentAssignments;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.Workforce.Application.EquipmentAssignments;

public sealed class CreateEquipmentAssignmentCommandHandler(IEquipmentAssignmentRepository repo, IEmployeeRepository employees, IWorkforceUnitOfWork uow, IClock clock) : ICommandHandler<CreateEquipmentAssignmentCommand, EquipmentAssignmentId> { public async Task<Result<EquipmentAssignmentId>> Handle(CreateEquipmentAssignmentCommand c, CancellationToken ct) { var e = await employees.GetByIdAsync(c.OrganizationId, c.EmployeeId, ct); if (e is null) return Result.Failure<EquipmentAssignmentId>(EmployeeErrors.NotFound); if (e.Status == EmploymentStatus.Ended) return Result.Failure<EquipmentAssignmentId>(EmployeeErrors.InvalidLifecycleTransition); if (c.StartDate < e.EmploymentStartDate || (e.EmploymentEndDate is DateOnly end && c.StartDate > end)) return Result.Failure<EquipmentAssignmentId>(EquipmentAssignmentErrors.InvalidPeriod); if (await repo.HasResourceOverlapAsync(c.OrganizationId, c.ResourceType, c.ResourceId, c.StartDate, c.PlannedEndDate, null, ct)) return Result.Failure<EquipmentAssignmentId>(EquipmentAssignmentErrors.ResourceAlreadyAssigned); var r = EquipmentAssignment.Create(c.Id, c.OrganizationId, c.EmployeeId, c.ResourceType, c.ResourceId, c.StartDate, c.PlannedEndDate, clock.UtcNow, c.ActorUserId); if (r.IsFailure) return Result.Failure<EquipmentAssignmentId>(r.Error); repo.Add(r.Value); await uow.CommitAsync(ct); return Result.Success(r.Value.Id); } }
public sealed class UpdateEquipmentAssignmentPlanCommandHandler(IEquipmentAssignmentRepository repo, IWorkforceUnitOfWork uow, IClock clock) : ICommandHandler<UpdateEquipmentAssignmentPlanCommand> { public async Task<Result> Handle(UpdateEquipmentAssignmentPlanCommand c, CancellationToken ct) { var x = await repo.GetAsync(c.OrganizationId, c.Id, true, ct); if (x is null) return Result.Failure(EquipmentAssignmentErrors.NotFound); if (await repo.HasResourceOverlapAsync(c.OrganizationId, x.ResourceType, x.ResourceId, c.StartDate, c.PlannedEndDate, c.Id, ct)) return Result.Failure(EquipmentAssignmentErrors.ResourceAlreadyAssigned); var r = x.UpdatePlan(c.StartDate, c.PlannedEndDate, clock.UtcNow, c.ActorUserId); if (r.IsFailure) return r; await uow.CommitAsync(ct); return Result.Success(); } }
public sealed class HandOverEquipmentAssignmentCommandHandler(IEquipmentAssignmentRepository repo, IWorkforceUnitOfWork uow, IClock clock) : ICommandHandler<HandOverEquipmentAssignmentCommand> { public async Task<Result> Handle(HandOverEquipmentAssignmentCommand c, CancellationToken ct) { var x = await repo.GetAsync(c.OrganizationId, c.Id, true, ct); if (x is null) return Result.Failure(EquipmentAssignmentErrors.NotFound); var r = x.HandOver(c.Condition, c.Notes, clock.UtcNow, c.ActorUserId); if (r.IsFailure) return r; await uow.CommitAsync(ct); return Result.Success(); } }
public sealed class ReturnEquipmentAssignmentCommandHandler(IEquipmentAssignmentRepository repo, IWorkforceUnitOfWork uow, IClock clock) : ICommandHandler<ReturnEquipmentAssignmentCommand> { public async Task<Result> Handle(ReturnEquipmentAssignmentCommand c, CancellationToken ct) { var x = await repo.GetAsync(c.OrganizationId, c.Id, true, ct); if (x is null) return Result.Failure(EquipmentAssignmentErrors.NotFound); var r = x.Return(c.ReturnedOn, c.Condition, c.Notes, clock.UtcNow, c.ActorUserId); if (r.IsFailure) return r; await uow.CommitAsync(ct); return Result.Success(); } }
public sealed class CancelEquipmentAssignmentCommandHandler(IEquipmentAssignmentRepository repo, IWorkforceUnitOfWork uow, IClock clock) : ICommandHandler<CancelEquipmentAssignmentCommand> { public async Task<Result> Handle(CancelEquipmentAssignmentCommand c, CancellationToken ct) { var x = await repo.GetAsync(c.OrganizationId, c.Id, true, ct); if (x is null) return Result.Failure(EquipmentAssignmentErrors.NotFound); var r = x.Cancel(c.Reason, clock.UtcNow, c.ActorUserId); if (r.IsFailure) return r; await uow.CommitAsync(ct); return Result.Success(); } }
public sealed class GetEquipmentAssignmentQueryHandler(IEquipmentAssignmentRepository repo) : IQueryHandler<GetEquipmentAssignmentQuery, EquipmentAssignmentResponse> { public async Task<Result<EquipmentAssignmentResponse>> Handle(GetEquipmentAssignmentQuery q, CancellationToken ct) { var x = await repo.GetAsync(q.OrganizationId, q.Id, false, ct); return x is null ? Result.Failure<EquipmentAssignmentResponse>(EquipmentAssignmentErrors.NotFound) : Result.Success(Map(x)); } internal static EquipmentAssignmentResponse Map(EquipmentAssignment x) => new(x.Id.Value, x.EmployeeId.Value, x.ResourceType.ToString(), x.ResourceId, x.StartDate, x.PlannedEndDate, x.ReturnedOn, x.Status.ToString(), x.HandoverCondition.ToString(), x.HandoverNotes, x.HandedOverAtUtc, x.HandedOverByUserId?.Value, x.ReturnCondition.ToString(), x.ReturnNotes, x.ReturnedAtUtc, x.ReturnedByUserId?.Value, x.CancellationReason); }
public sealed class GetEquipmentAssignmentsQueryHandler(IEquipmentAssignmentRepository repo) : IQueryHandler<GetEquipmentAssignmentsQuery, IReadOnlyList<EquipmentAssignmentResponse>> { public async Task<Result<IReadOnlyList<EquipmentAssignmentResponse>>> Handle(GetEquipmentAssignmentsQuery q, CancellationToken ct) => Result.Success<IReadOnlyList<EquipmentAssignmentResponse>>((await repo.ListAsync(q.OrganizationId, q.EmployeeId, q.Status, q.ResourceType, ct)).Select(GetEquipmentAssignmentQueryHandler.Map).ToArray()); }
