using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.ProfessionalMarketplace.Application.Persistence;
using DriveOS.Modules.ProfessionalMarketplace.Domain.Engagements;
using DriveOS.Modules.ProfessionalMarketplace.Domain.Reviews;
using DriveOS.Modules.ProfessionalMarketplace.Domain.ProfessionalProfiles;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.ProfessionalMarketplace.Application.Reviews;
public sealed class CreateProfessionalReviewCommandHandler(IProfessionalReviewRepository reviews,IProfessionalEngagementRepository engagements,IProfessionalMarketplaceUnitOfWork uow,IClock clock):ICommandHandler<CreateProfessionalReviewCommand,ProfessionalReviewId>
{
 public async Task<Result<ProfessionalReviewId>> Handle(CreateProfessionalReviewCommand c,CancellationToken ct){if(await reviews.ExistsForEngagementAsync(c.EngagementId,ct))return Result.Failure<ProfessionalReviewId>(ProfessionalReviewErrors.DuplicateReview);var e=await engagements.GetAsync(c.EngagementId,false,ct);if(e is null||e.OrganizationId!=c.OrganizationId)return Result.Failure<ProfessionalReviewId>(ProfessionalEngagementErrors.NotFound);var created=ProfessionalReview.Create(c.Id,e,c.ActorUserId,c.Ratings,c.Comment,clock.UtcNow);if(created.IsFailure)return Result.Failure<ProfessionalReviewId>(created.Error);reviews.Add(created.Value);await uow.CommitAsync(ct);return Result.Success(created.Value.Id);}
}
public sealed class RespondProfessionalReviewCommandHandler(IProfessionalReviewRepository reviews,IProfessionalProfileRepository profiles,IProfessionalMarketplaceUnitOfWork uow,IClock clock):ICommandHandler<RespondProfessionalReviewCommand>{public async Task<Result> Handle(RespondProfessionalReviewCommand c,CancellationToken ct){var profile=await profiles.FindByUserAsync(c.ActorUserId,ct);if(profile is null||profile.Id!=c.ProfileId)return Result.Failure(ProfessionalReviewErrors.ProfileAccessDenied);var x=await reviews.GetAsync(c.Id,true,ct);if(x is null||x.ProfessionalProfileId!=profile.Id)return Result.Failure(ProfessionalReviewErrors.NotFound);var r=x.Respond(c.Response,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class ReportProfessionalReviewCommandHandler(IProfessionalReviewRepository reviews,IProfessionalReviewReportRepository reports,IProfessionalProfileRepository profiles,IProfessionalMarketplaceUnitOfWork uow,IClock clock):ICommandHandler<ReportProfessionalReviewCommand,ProfessionalReviewReportId>{public async Task<Result<ProfessionalReviewReportId>> Handle(ReportProfessionalReviewCommand c,CancellationToken ct){var review=await reviews.GetAsync(c.ReviewId,false,ct);if(review is null)return Result.Failure<ProfessionalReviewReportId>(ProfessionalReviewErrors.NotFound);var actorProfile=await profiles.FindByUserAsync(c.ActorUserId,ct);var isReviewingOrganization=review.OrganizationId==c.OrganizationId;var isReviewedProfessional=actorProfile is not null&&actorProfile.Id==review.ProfessionalProfileId&&actorProfile.ProviderOrganizationId==c.OrganizationId;if(!isReviewingOrganization&&!isReviewedProfessional)return Result.Failure<ProfessionalReviewReportId>(ProfessionalReviewErrors.OrganizationMismatch);if(await reports.OpenReportExistsAsync(c.ReviewId,c.ActorUserId,ct))return Result.Failure<ProfessionalReviewReportId>(ProfessionalReviewErrors.DuplicateOpenReport);var created=ProfessionalReviewReport.Create(c.Id,c.ReviewId,c.OrganizationId,c.ActorUserId,c.ReasonCode,c.Details,clock.UtcNow);if(created.IsFailure)return Result.Failure<ProfessionalReviewReportId>(created.Error);reports.Add(created.Value);await uow.CommitAsync(ct);return Result.Success(created.Value.Id);}}
public sealed class HideProfessionalReviewCommandHandler(IProfessionalReviewRepository reviews,IProfessionalMarketplaceUnitOfWork uow,IClock clock):ICommandHandler<HideProfessionalReviewCommand>{public async Task<Result> Handle(HideProfessionalReviewCommand c,CancellationToken ct){var x=await reviews.GetAsync(c.Id,true,ct);if(x is null)return Result.Failure(ProfessionalReviewErrors.NotFound);var r=x.Hide(c.Reason,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class RestoreProfessionalReviewCommandHandler(IProfessionalReviewRepository reviews,IProfessionalMarketplaceUnitOfWork uow,IClock clock):ICommandHandler<RestoreProfessionalReviewCommand>{public async Task<Result> Handle(RestoreProfessionalReviewCommand c,CancellationToken ct){var x=await reviews.GetAsync(c.Id,true,ct);if(x is null)return Result.Failure(ProfessionalReviewErrors.NotFound);var r=x.Restore(clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class ResolveProfessionalReviewReportCommandHandler(IProfessionalReviewReportRepository reports,IProfessionalMarketplaceUnitOfWork uow,IClock clock):ICommandHandler<ResolveProfessionalReviewReportCommand>{public async Task<Result> Handle(ResolveProfessionalReviewReportCommand c,CancellationToken ct){var x=await reports.GetAsync(c.Id,true,ct);if(x is null)return Result.Failure(ProfessionalReviewErrors.ReportNotFound);var r=x.Resolve(c.Resolution,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class GetProfessionalReputationQueryHandler(IProfessionalReviewRepository reviews):IQueryHandler<GetProfessionalReputationQuery,ProfessionalReputationResponse>
{
 public async Task<Result<ProfessionalReputationResponse>> Handle(GetProfessionalReputationQuery q,CancellationToken ct){var items=await reviews.ListPublishedByProfileAsync(q.ProfileId,ct);decimal Avg(Func<ProfessionalReview,int> f)=>items.Count==0?0m:decimal.Round((decimal)items.Average(x=>f(x)),2);var dto=items.Select(x=>new ProfessionalReviewResponse(x.Id.Value,x.OrganizationId.Value,x.EngagementId.Value,x.OverallScore,x.Ratings,x.Comment,x.ProfessionalResponse,x.CreatedAtUtc)).ToArray();return Result.Success(new ProfessionalReputationResponse(q.ProfileId.Value,items.Count==0?0m:decimal.Round(items.Average(x=>x.OverallScore),2),items.Count,Avg(x=>x.Ratings.Reliability),Avg(x=>x.Ratings.Pedagogy),Avg(x=>x.Ratings.Communication),Avg(x=>x.Ratings.Punctuality),dto));}
}

public sealed class GetProfessionalReviewModerationQueryHandler(IProfessionalReviewRepository reviews,IProfessionalReviewReportRepository reports):IQueryHandler<GetProfessionalReviewModerationQuery,ProfessionalReviewModerationResponse>
{
 public async Task<Result<ProfessionalReviewModerationResponse>> Handle(GetProfessionalReviewModerationQuery q,CancellationToken ct){var items=await reviews.ListByProfileAsync(q.ProfileId,ct);var reportItems=await reports.ListByProfileAsync(q.ProfileId,ct);var grouped=reportItems.GroupBy(x=>x.ReviewId).ToDictionary(x=>x.Key,x=>x.ToArray());var dto=items.Select(x=>new ModeratedProfessionalReviewResponse(x.Id.Value,x.OrganizationId.Value,x.EngagementId.Value,x.OverallScore,x.Ratings,x.Comment,x.ProfessionalResponse,x.CreatedAtUtc,x.Status.ToString(),x.RespondedAtUtc,x.HiddenAtUtc,x.ModerationReason,grouped.TryGetValue(x.Id,out var rr)?rr.Select(r=>new ProfessionalReviewReportResponse(r.Id.Value,r.ReasonCode,r.Details,r.Status.ToString(),r.Resolution,r.CreatedAtUtc,r.ResolvedAtUtc)).ToArray():Array.Empty<ProfessionalReviewReportResponse>())).ToArray();return Result.Success(new ProfessionalReviewModerationResponse(q.ProfileId.Value,dto));}
}
