using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.Workforce.Application.Persistence;
using DriveOS.Modules.Workforce.Domain.Employees;
using DriveOS.Modules.Workforce.Domain.Timesheets;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.Workforce.Application.Timesheets;

public sealed class CreateTimesheetCommandHandler(ITimesheetRepository repo,IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<CreateTimesheetCommand,TimesheetId>
{
 public async Task<Result<TimesheetId>> Handle(CreateTimesheetCommand c,CancellationToken ct){var employee=await employees.GetByIdAsync(c.OrganizationId,c.EmployeeId,ct);if(employee is null)return Result.Failure<TimesheetId>(EmployeeErrors.NotFound);if(c.PeriodFrom<employee.EmploymentStartDate||(employee.EmploymentEndDate is DateOnly end&&c.PeriodTo>end))return Result.Failure<TimesheetId>(TimesheetErrors.InvalidPeriod);if(await repo.HasOverlapAsync(c.OrganizationId,c.EmployeeId,c.PeriodFrom,c.PeriodTo,null,ct))return Result.Failure<TimesheetId>(TimesheetErrors.OverlappingPeriod);var r=Timesheet.Create(c.TimesheetId,c.OrganizationId,c.EmployeeId,c.PeriodFrom,c.PeriodTo,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return Result.Failure<TimesheetId>(r.Error);repo.Add(r.Value);await uow.CommitAsync(ct);return Result.Success(r.Value.Id);}
}
public sealed class AddTimesheetEntryCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<AddTimesheetEntryCommand,TimesheetEntryId>
{public async Task<Result<TimesheetEntryId>> Handle(AddTimesheetEntryCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure<TimesheetEntryId>(TimesheetErrors.NotFound);var r=x.AddEntry(c.EntryId,c.Date,c.ActivityType,c.Hours,c.Description,c.Source,c.SourceReference,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return Result.Failure<TimesheetEntryId>(r.Error);await uow.CommitAsync(ct);return r;}}
public sealed class UpdateTimesheetEntryCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<UpdateTimesheetEntryCommand>
{public async Task<Result> Handle(UpdateTimesheetEntryCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.UpdateEntry(c.EntryId,c.Date,c.ActivityType,c.Hours,c.Description,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class RemoveTimesheetEntryCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<RemoveTimesheetEntryCommand>
{public async Task<Result> Handle(RemoveTimesheetEntryCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.RemoveEntry(c.EntryId,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class SubmitTimesheetCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<SubmitTimesheetCommand>{public async Task<Result> Handle(SubmitTimesheetCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.Submit(clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class StartTimesheetReviewCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<StartTimesheetReviewCommand>{public async Task<Result> Handle(StartTimesheetReviewCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.StartReview(clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class ApproveTimesheetCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<ApproveTimesheetCommand>{public async Task<Result> Handle(ApproveTimesheetCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.Approve(clock.UtcNow,c.ActorUserId,c.Reason);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class RejectTimesheetCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<RejectTimesheetCommand>{public async Task<Result> Handle(RejectTimesheetCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.Reject(clock.UtcNow,c.ActorUserId,c.Reason);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class LockTimesheetCommandHandler(ITimesheetRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<LockTimesheetCommand>{public async Task<Result> Handle(LockTimesheetCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.TimesheetId,true,ct);if(x is null)return Result.Failure(TimesheetErrors.NotFound);var r=x.Lock(clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class GetTimesheetQueryHandler(ITimesheetRepository repo):IQueryHandler<GetTimesheetQuery,TimesheetResponse>
{public async Task<Result<TimesheetResponse>> Handle(GetTimesheetQuery q,CancellationToken ct){var x=await repo.GetAsync(q.OrganizationId,q.TimesheetId,false,ct);return x is null?Result.Failure<TimesheetResponse>(TimesheetErrors.NotFound):Result.Success(Map(x));}internal static TimesheetResponse Map(Timesheet x)=>new(x.Id.Value,x.EmployeeId.Value,x.PeriodFrom,x.PeriodTo,x.Status.ToString(),x.TotalHours,x.SubmittedAtUtc,x.SubmittedByUserId?.Value,x.ReviewStartedAtUtc,x.ReviewerUserId?.Value,x.DecidedAtUtc,x.DecidedByUserId?.Value,x.DecisionReason,x.LockedAtUtc,x.LockedByUserId?.Value,x.Entries.OrderBy(e=>e.Date).ThenBy(e=>e.Id.Value).Select(e=>new TimesheetEntryResponse(e.Id.Value,e.Date,e.ActivityType.ToString(),e.Hours,e.Description,e.Source.ToString(),e.SourceReference)).ToArray());}
public sealed class GetTimesheetsQueryHandler(ITimesheetRepository repo):IQueryHandler<GetTimesheetsQuery,IReadOnlyList<TimesheetResponse>>{public async Task<Result<IReadOnlyList<TimesheetResponse>>> Handle(GetTimesheetsQuery q,CancellationToken ct)=>Result.Success<IReadOnlyList<TimesheetResponse>>((await repo.ListAsync(q.OrganizationId,q.EmployeeId,q.Status,q.From,q.To,ct)).Select(GetTimesheetQueryHandler.Map).ToArray());}
