using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.Workforce.Application.Persistence;
using DriveOS.Modules.Workforce.Domain.Employees;
using DriveOS.Modules.Workforce.Domain.EmploymentContracts;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.Workforce.Application.EmploymentContracts;
public sealed class GetEmploymentContractsQueryHandler(IEmployeeRepository employees):IQueryHandler<GetEmploymentContractsQuery,IReadOnlyList<EmploymentContractResponse>>
{public async Task<Result<IReadOnlyList<EmploymentContractResponse>>> Handle(GetEmploymentContractsQuery q,CancellationToken ct){var e=await employees.GetByIdAsync(q.OrganizationId,q.EmployeeId,ct);if(e is null)return Result.Failure<IReadOnlyList<EmploymentContractResponse>>(EmployeeErrors.NotFound);return Result.Success<IReadOnlyList<EmploymentContractResponse>>(e.EmploymentContracts.OrderByDescending(x=>x.StartDate).Select(x=>new EmploymentContractResponse(x.Id.Value,x.ContractType.ToString(),x.StartDate,x.EndDate,x.ContractualWeeklyHours,x.PrimaryJobPositionId?.Value,x.Status.ToString(),x.ContractDocumentId?.Value,x.SignatureProcessId?.Value,x.CreatedAtUtc,x.LastModifiedAtUtc)).ToArray());}}
public sealed class AddEmploymentContractCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<AddEmploymentContractCommand,EmploymentContractId>
{public async Task<Result<EmploymentContractId>> Handle(AddEmploymentContractCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure<EmploymentContractId>(EmployeeErrors.NotFound);var r=e.AddEmploymentContract(c.ContractId,c.ContractType,c.StartDate,c.EndDate,c.ContractualWeeklyHours,c.PrimaryJobPositionId,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return r;}}
public sealed class UpdateEmploymentContractTermsCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<UpdateEmploymentContractTermsCommand>
{public async Task<Result> Handle(UpdateEmploymentContractTermsCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.UpdateEmploymentContractTerms(c.ContractId,c.StartDate,c.EndDate,c.ContractualWeeklyHours,c.PrimaryJobPositionId,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class LinkEmploymentContractDocumentCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<LinkEmploymentContractDocumentCommand>
{public async Task<Result> Handle(LinkEmploymentContractDocumentCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.LinkEmploymentContractDocument(c.ContractId,c.ContractDocumentId,c.SignatureProcessId,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class MarkEmploymentContractSignedCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<MarkEmploymentContractSignedCommand>
{public async Task<Result> Handle(MarkEmploymentContractSignedCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.MarkEmploymentContractSigned(c.ContractId,c.SignatureProcessId,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class ActivateEmploymentContractCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<ActivateEmploymentContractCommand>
{public async Task<Result> Handle(ActivateEmploymentContractCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.ActivateEmploymentContract(c.ContractId,c.ActivationDate,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class TerminateEmploymentContractCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<TerminateEmploymentContractCommand>
{public async Task<Result> Handle(TerminateEmploymentContractCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.TerminateEmploymentContract(c.ContractId,c.EndDate,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class CancelEmploymentContractCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<CancelEmploymentContractCommand>
{public async Task<Result> Handle(CancelEmploymentContractCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.CancelEmploymentContract(c.ContractId,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
