@DriveOS.Api_HostAddress = http://localhost:5221

GET {{DriveOS.Api_HostAddress}}/health
Accept: application/json

###


POST {{DriveOS.Api_HostAddress}}/api/organizations
Content-Type: application/json
{
  "name": "Test Organization"
}

