using DriveOS.Application.Abstractions.Messaging;using DriveOS.SharedKernel.Identifiers;using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.CurriculumPedagogy.Application.RemediationPlans;
public sealed record RemediationTargetRequest(CompetencyId CompetencyId,string Objective);
public sealed record CreateRemediationPlanCommand(OrganizationId OrganizationId,TrainingPathId TrainingPathId,UserId ResponsibleUserId,PedagogicalReviewId? SourceReviewId,string Recommendation,decimal? RecommendedPracticalHours,int? RecommendedSessions,DateOnly ReviewDate,IReadOnlyCollection<RemediationTargetRequest> Targets):ICommand<RemediationPlanId>;
public sealed record ActivateRemediationPlanCommand(OrganizationId OrganizationId,RemediationPlanId PlanId):ICommand;
public sealed record CompleteRemediationPlanCommand(OrganizationId OrganizationId,RemediationPlanId PlanId):ICommand;
public sealed record CancelRemediationPlanCommand(OrganizationId OrganizationId,RemediationPlanId PlanId,string Reason):ICommand;
public static class RemediationPlanApplicationErrors{public static readonly Error TrainingPathNotFound=Error.NotFound("CurriculumPedagogy.RemediationPlan.TrainingPath.NotFound","errors.curriculumPedagogy.remediationPlan.trainingPathNotFound");public static readonly Error TrainingPathNotEligible=Error.Conflict("CurriculumPedagogy.RemediationPlan.TrainingPath.NotEligible","errors.curriculumPedagogy.remediationPlan.trainingPathNotEligible");public static readonly Error OpenPlanExists=Error.Conflict("CurriculumPedagogy.RemediationPlan.OpenPlan.Exists","errors.curriculumPedagogy.remediationPlan.openPlanExists");public static readonly Error CompetencyNotFound=Error.NotFound("CurriculumPedagogy.RemediationPlan.Competency.NotFound","errors.curriculumPedagogy.remediationPlan.competencyNotFound");public static readonly Error SourceReviewInvalid=Error.Conflict("CurriculumPedagogy.RemediationPlan.SourceReview.Invalid","errors.curriculumPedagogy.remediationPlan.sourceReviewInvalid");public static readonly Error NotFound=Error.NotFound("CurriculumPedagogy.RemediationPlan.NotFound","errors.curriculumPedagogy.remediationPlan.notFound");}
public sealed record RemediationTargetResponse(Guid Id,Guid CompetencyId,string Objective);
public sealed record RemediationPlanResponse(Guid Id,Guid StudentId,Guid TrainingPathId,Guid ResponsibleUserId,Guid? SourcePedagogicalReviewId,string Recommendation,decimal? RecommendedPracticalHours,int? RecommendedSessions,DateOnly ReviewDate,string Status,DateTimeOffset PlanCreatedAtUtc,DateTimeOffset? ActivatedAtUtc,DateTimeOffset? CompletedAtUtc,DateTimeOffset? CancelledAtUtc,string? CancellationReason,IReadOnlyCollection<RemediationTargetResponse> Targets);
public interface IRemediationPlanReadService{Task<IReadOnlyCollection<RemediationPlanResponse>>ListAsync(OrganizationId organizationId,TrainingPathId trainingPathId,CancellationToken ct=default);Task<RemediationPlanResponse?>GetAsync(OrganizationId organizationId,RemediationPlanId id,CancellationToken ct=default);}
