using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.Workforce.Application.Persistence;
using DriveOS.Modules.Workforce.Domain.Employees;
using DriveOS.Modules.Workforce.Domain.Qualifications;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.Workforce.Application.Qualifications;

public sealed class GetEmployeeQualificationsQueryHandler(IEmployeeRepository employees):IQueryHandler<GetEmployeeQualificationsQuery,IReadOnlyList<EmployeeQualificationResponse>>
{ public async Task<Result<IReadOnlyList<EmployeeQualificationResponse>>> Handle(GetEmployeeQualificationsQuery q,CancellationToken ct){var e=await employees.GetByIdAsync(q.OrganizationId,q.EmployeeId,ct);if(e is null)return Result.Failure<IReadOnlyList<EmployeeQualificationResponse>>(EmployeeErrors.NotFound);return Result.Success<IReadOnlyList<EmployeeQualificationResponse>>(e.Qualifications.OrderByDescending(x=>x.DeclaredAtUtc).Select(Map).ToArray());} internal static EmployeeQualificationResponse Map(EmployeeQualification x)=>new(x.Id.Value,x.CountryCode,x.QualificationType,x.Title,x.Identifier,x.IssuingAuthority,x.IssuedOn,x.ExpiresOn,x.Source.ToString(),x.Status.ToString(),x.DeclaredAtUtc,x.VerifiedAtUtc,x.VerificationMethod,x.DecisionReason,x.SupersededById?.Value); }
public sealed class DeclareEmployeeQualificationCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<DeclareEmployeeQualificationCommand,EmployeeQualificationId>
{ public async Task<Result<EmployeeQualificationId>> Handle(DeclareEmployeeQualificationCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure<EmployeeQualificationId>(EmployeeErrors.NotFound);var r=e.DeclareQualification(c.QualificationId,c.CountryCode,c.QualificationType,c.Title,c.Identifier,c.IssuingAuthority,c.IssuedOn,c.ExpiresOn,c.Source,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return r;} }
public sealed class VerifyEmployeeQualificationCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<VerifyEmployeeQualificationCommand>
{ public async Task<Result> Handle(VerifyEmployeeQualificationCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.VerifyQualification(c.QualificationId,c.VerificationMethod,c.Reason,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();} }
public sealed class RejectEmployeeQualificationCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<RejectEmployeeQualificationCommand>
{ public async Task<Result> Handle(RejectEmployeeQualificationCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.RejectQualification(c.QualificationId,c.Reason,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();} }
public sealed class GetInstructorAuthorizationsQueryHandler(IEmployeeRepository employees):IQueryHandler<GetInstructorAuthorizationsQuery,IReadOnlyList<InstructorAuthorizationResponse>>
{ public async Task<Result<IReadOnlyList<InstructorAuthorizationResponse>>> Handle(GetInstructorAuthorizationsQuery q,CancellationToken ct){var e=await employees.GetByIdAsync(q.OrganizationId,q.EmployeeId,ct);if(e is null)return Result.Failure<IReadOnlyList<InstructorAuthorizationResponse>>(EmployeeErrors.NotFound);return Result.Success<IReadOnlyList<InstructorAuthorizationResponse>>(e.InstructorAuthorizations.OrderByDescending(x=>x.DeclaredAtUtc).Select(Map).ToArray());} internal static InstructorAuthorizationResponse Map(InstructorAuthorization x)=>new(x.Id.Value,x.CountryCode,x.AuthorizationType,x.Identifier,x.IssuingAuthority,x.JurisdictionCode,x.LicenseCategoryCode,x.IssuedOn,x.ExpiresOn,x.Source.ToString(),x.Status.ToString(),x.DeclaredAtUtc,x.VerifiedAtUtc,x.VerificationMethod,x.DecisionReason,x.SupersededById?.Value); }
public sealed class DeclareInstructorAuthorizationCommandHandler(IEmployeeRepository employees, DriveOS.Modules.Workforce.Domain.JobPositions.IJobPositionRepository positions,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<DeclareInstructorAuthorizationCommand,InstructorAuthorizationId>
{ public async Task<Result<InstructorAuthorizationId>> Handle(DeclareInstructorAuthorizationCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure<InstructorAuthorizationId>(EmployeeErrors.NotFound); DateOnly at=c.IssuedOn??DateOnly.FromDateTime(clock.UtcNow.UtcDateTime); bool instructor=false; foreach(var a in e.JobPositionAssignments.Where(x=>x.Status!=DriveOS.Modules.Workforce.Domain.JobPositions.EmployeeJobPositionAssignmentStatus.Cancelled && x.StartDate<=at && (!x.EndDate.HasValue||x.EndDate.Value>=at))){var p=await positions.GetByIdAsync(c.OrganizationId,a.JobPositionId,ct); if(p?.ProfessionalFunction==DriveOS.Modules.Workforce.Domain.JobPositions.ProfessionalFunction.Instructor){instructor=true;break;}} if(!instructor)return Result.Failure<InstructorAuthorizationId>(QualificationErrors.InstructorFunctionRequired);var r=e.DeclareInstructorAuthorization(c.AuthorizationId,c.CountryCode,c.AuthorizationType,c.Identifier,c.IssuingAuthority,c.JurisdictionCode,c.LicenseCategoryCode,c.IssuedOn,c.ExpiresOn,c.Source,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return r;} }
public sealed class VerifyInstructorAuthorizationCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<VerifyInstructorAuthorizationCommand>
{ public async Task<Result> Handle(VerifyInstructorAuthorizationCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.VerifyInstructorAuthorization(c.AuthorizationId,c.VerificationMethod,c.Reason,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();} }
public sealed class RejectInstructorAuthorizationCommandHandler(IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<RejectInstructorAuthorizationCommand>
{ public async Task<Result> Handle(RejectInstructorAuthorizationCommand c,CancellationToken ct){var e=await employees.GetByIdForUpdateAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure(EmployeeErrors.NotFound);var r=e.RejectInstructorAuthorization(c.AuthorizationId,c.Reason,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();} }
