// <auto-generated />
using System;
using DriveOS.Modules.Workforce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveOS.Modules.Workforce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkforceDbContext))]
    partial class WorkforceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workforce")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.EmployeeDocuments.EmployeeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Confidentiality")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupersededByEmployeeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DocumentReferenceId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ExpiresOn");

                    b.HasIndex("OrganizationId", "EmployeeId", "Category");

                    b.HasIndex("OrganizationId", "EmployeeId", "Status");

                    b.ToTable("employee_documents", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EmploymentEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EmploymentStartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RehiredFromEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("rehired_from_employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployerOrganizationId", "EmployeeNumber")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Ended'");

                    b.HasIndex("EmployerOrganizationId", "RehiredFromEmployeeId");

                    b.HasIndex("EmployerOrganizationId", "Status");

                    b.HasIndex("EmployerOrganizationId", "PersonId", "Status");

                    b.HasIndex("EmployerOrganizationId", "UserId", "Status");

                    b.ToTable("employees", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.EquipmentAssignments.EquipmentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("HandedOverAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandedOverByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("HandoverCondition")
                        .HasColumnType("integer");

                    b.Property<string>("HandoverNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnCondition")
                        .HasColumnType("integer");

                    b.Property<string>("ReturnNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReturnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReturnedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ReturnedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "Status");

                    b.HasIndex("OrganizationId", "StartDate", "PlannedEndDate");

                    b.HasIndex("OrganizationId", "ResourceType", "ResourceId", "Status");

                    b.ToTable("equipment_assignments", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.JobPositions.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfessionalFunction")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ProfessionalFunction", "Status");

                    b.ToTable("job_positions", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.LeavePolicies.LeavePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowHalfDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaximumConsecutiveDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumNoticeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresEvidence")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CountryCode", "Code")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "CountryCode", "Status");

                    b.ToTable("leave_policies", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.LeaveRequests.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowHalfDay")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EndPortion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("EvidenceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeavePolicyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaximumConsecutiveDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumNoticeDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresEvidence")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StartPortion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "Status");

                    b.HasIndex("OrganizationId", "LeavePolicyId", "Status");

                    b.HasIndex("OrganizationId", "StartDate", "EndDate");

                    b.ToTable("leave_requests", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.Offboarding.OffboardingProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "Status");

                    b.ToTable("offboarding_processes", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.PerformanceReviews.PerformanceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeComment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objectives")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverallAssessment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "Status");

                    b.HasIndex("OrganizationId", "PeriodFrom", "PeriodTo");

                    b.ToTable("performance_reviews", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.PerformanceReviews.PerformanceReviewCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<Guid?>("performance_review_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("performance_review_id", "Code")
                        .IsUnique();

                    b.ToTable("performance_review_criteria", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.ProfessionalRestrictions.ProfessionalRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActivatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Activity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicenseCategoryCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LiftReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LiftedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LiftedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupportingDocumentReferenceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "Status");

                    b.HasIndex("OrganizationId", "EmployeeId", "CountryCode", "LicenseCategoryCode");

                    b.HasIndex("OrganizationId", "Activity", "Status", "StartDate", "EndDate");

                    b.ToTable("professional_restrictions", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.Timesheets.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ReviewStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Status");

                    b.HasIndex("OrganizationId", "EmployeeId", "PeriodFrom", "PeriodTo");

                    b.ToTable("timesheets", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.WorkingTime.WorkingTimePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ContractualDailyHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("ContractualWeeklyHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxWorkingDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "EffectiveFrom");

                    b.ToTable("working_time_policies", "workforce");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.Employees.Employee", b =>
                {
                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.BranchAssignments.EmployeeBranchAssignment", "BranchAssignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("branch_id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<Guid>("CreatedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_user_id");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<DateTimeOffset?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at_utc");

                            b1.Property<Guid?>("LastModifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modified_by_user_id");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id", "BranchId", "StartDate");

                            b1.HasIndex("employee_id", "IsPrimary", "StartDate", "EndDate");

                            b1.ToTable("employee_branch_assignments", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("employee_id");
                        });

                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.EmploymentContracts.EmploymentContract", "EmploymentContracts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ContractDocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("contract_document_id");

                            b1.Property<string>("ContractType")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("contract_type");

                            b1.Property<decimal?>("ContractualWeeklyHours")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("contractual_weekly_hours");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<Guid>("CreatedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_user_id");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateTimeOffset?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at_utc");

                            b1.Property<Guid?>("LastModifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modified_by_user_id");

                            b1.Property<Guid?>("PrimaryJobPositionId")
                                .HasColumnType("uuid")
                                .HasColumnName("primary_job_position_id");

                            b1.Property<Guid?>("SignatureProcessId")
                                .HasColumnType("uuid")
                                .HasColumnName("signature_process_id");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("status");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractDocumentId");

                            b1.HasIndex("employee_id", "Status");

                            b1.HasIndex("employee_id", "StartDate", "EndDate");

                            b1.ToTable("employee_employment_contracts", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("employee_id");
                        });

                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.JobPositions.EmployeeJobPositionAssignment", "JobPositionAssignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("branch_id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<Guid>("CreatedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_user_id");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<Guid>("JobPositionId")
                                .HasColumnType("uuid")
                                .HasColumnName("job_position_id");

                            b1.Property<DateTimeOffset?>("LastModifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at_utc");

                            b1.Property<Guid?>("LastModifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("last_modified_by_user_id");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id", "JobPositionId", "StartDate");

                            b1.HasIndex("employee_id", "BranchId", "StartDate", "EndDate");

                            b1.HasIndex("employee_id", "IsPrimary", "StartDate", "EndDate");

                            b1.ToTable("employee_job_position_assignments", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("employee_id");
                        });

                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.Qualifications.EmployeeQualification", "Qualifications", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("DecisionReason")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("DeclaredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("DeclaredByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("declared_by_user_id");

                            b1.Property<DateOnly?>("ExpiresOn")
                                .HasColumnType("date");

                            b1.Property<string>("Identifier")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("identifier");

                            b1.Property<DateOnly?>("IssuedOn")
                                .HasColumnType("date");

                            b1.Property<string>("IssuingAuthority")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("issuing_authority");

                            b1.Property<string>("QualificationType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("qualification_type");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("source");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("status");

                            b1.Property<Guid?>("SupersededById")
                                .HasColumnType("uuid")
                                .HasColumnName("superseded_by_id");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("title");

                            b1.Property<string>("VerificationMethod")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("verified_by_user_id");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id", "CountryCode", "QualificationType", "Status");

                            b1.ToTable("employee_qualifications", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("employee_id");
                        });

                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.Qualifications.InstructorAuthorization", "InstructorAuthorizations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AuthorizationType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("authorization_type");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("DecisionReason")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("DeclaredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("DeclaredByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("declared_by_user_id");

                            b1.Property<DateOnly?>("ExpiresOn")
                                .HasColumnType("date");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("identifier");

                            b1.Property<DateOnly?>("IssuedOn")
                                .HasColumnType("date");

                            b1.Property<string>("IssuingAuthority")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("issuing_authority");

                            b1.Property<string>("JurisdictionCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("jurisdiction_code");

                            b1.Property<string>("LicenseCategoryCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("license_category_code");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("source");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("status");

                            b1.Property<Guid?>("SupersededById")
                                .HasColumnType("uuid")
                                .HasColumnName("superseded_by_id");

                            b1.Property<string>("VerificationMethod")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("verified_by_user_id");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id", "CountryCode", "AuthorizationType", "LicenseCategoryCode", "Status");

                            b1.ToTable("employee_instructor_authorizations", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("employee_id");
                        });

                    b.Navigation("BranchAssignments");

                    b.Navigation("EmploymentContracts");

                    b.Navigation("InstructorAuthorizations");

                    b.Navigation("JobPositionAssignments");

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.Offboarding.OffboardingProcess", b =>
                {
                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.Offboarding.OffboardingChecklistItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("BlockerCount")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsAutomatic")
                                .HasColumnType("boolean");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateTimeOffset?>("LastEvaluatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Note")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<DateTimeOffset?>("ResolvedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("ResolvedByUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("WaiverReason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("offboarding_process_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("offboarding_process_id", "Kind")
                                .IsUnique();

                            b1.ToTable("offboarding_checklist_items", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("offboarding_process_id");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.PerformanceReviews.PerformanceReviewCriterion", b =>
                {
                    b.HasOne("DriveOS.Modules.Workforce.Domain.PerformanceReviews.PerformanceReview", null)
                        .WithMany("Criteria")
                        .HasForeignKey("performance_review_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.Timesheets.Timesheet", b =>
                {
                    b.OwnsMany("DriveOS.Modules.Workforce.Domain.Timesheets.TimesheetEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("ActivityType")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("Description")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<decimal>("Hours")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)");

                            b1.Property<int>("Source")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceReference")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<Guid>("timesheet_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("timesheet_id", "Date");

                            b1.ToTable("timesheet_entries", "workforce");

                            b1.WithOwner()
                                .HasForeignKey("timesheet_id");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DriveOS.Modules.Workforce.Domain.PerformanceReviews.PerformanceReview", b =>
                {
                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
