using DriveOS.Modules.FundingBilling.Domain.CreditNotes;
using DriveOS.SharedKernel.Identifiers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace DriveOS.Modules.FundingBilling.Infrastructure.Persistence.Configurations;
internal sealed class CreditNoteConfiguration:IEntityTypeConfiguration<CreditNote>
{
 public void Configure(EntityTypeBuilder<CreditNote> b){b.ToTable("credit_notes");b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasColumnName("id").HasConversion(x=>x.Value,x=>new CreditNoteId(x)).ValueGeneratedNever();b.Property(x=>x.OrganizationId).HasColumnName("organization_id").HasConversion(x=>x.Value,x=>new OrganizationId(x)).IsRequired();b.Property(x=>x.BillingAccountId).HasColumnName("billing_account_id").HasConversion(x=>x.Value,x=>new BillingAccountId(x)).IsRequired();b.Property(x=>x.InvoiceId).HasColumnName("invoice_id").HasConversion(x=>x.Value,x=>new InvoiceId(x)).IsRequired();b.Property(x=>x.Currency).HasColumnName("currency").HasMaxLength(3).IsRequired();b.Property(x=>x.Reason).HasColumnName("reason").HasMaxLength(1000).IsRequired();b.Property(x=>x.CreditNoteNumber).HasColumnName("credit_note_number").HasMaxLength(80);b.Property(x=>x.IssueDate).HasColumnName("issue_date");b.Property(x=>x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(30);b.Property(x=>x.IssuedByUserId).HasColumnName("issued_by_user_id").HasConversion(x=>x.HasValue?x.Value.Value:(Guid?)null,x=>x.HasValue?new UserId(x.Value):null);b.Property(x=>x.IssuedAtUtc).HasColumnName("issued_at_utc");b.Property(x=>x.CreatedAtUtc).HasColumnName("created_at_utc");b.Property(x=>x.CreatedByUserId).HasColumnName("created_by_user_id").HasConversion(x=>x.HasValue?x.Value.Value:(Guid?)null,x=>x.HasValue?new UserId(x.Value):null);b.Property(x=>x.LastModifiedAtUtc).HasColumnName("last_modified_at_utc");b.Property(x=>x.LastModifiedByUserId).HasColumnName("last_modified_by_user_id").HasConversion(x=>x.HasValue?x.Value.Value:(Guid?)null,x=>x.HasValue?new UserId(x.Value):null);b.Ignore(x=>x.Subtotal);b.Ignore(x=>x.TaxAmount);b.Ignore(x=>x.TotalAmount);b.Ignore(x=>x.DomainEvents);b.HasIndex(x=>new{x.OrganizationId,x.CreditNoteNumber}).IsUnique().HasFilter("credit_note_number IS NOT NULL");b.HasMany(x=>x.Lines).WithOne().HasForeignKey(x=>x.CreditNoteId).OnDelete(DeleteBehavior.Cascade);b.Navigation(x=>x.Lines).UsePropertyAccessMode(PropertyAccessMode.Field);}
}
internal sealed class CreditNoteLineConfiguration:IEntityTypeConfiguration<CreditNoteLine>
{
 public void Configure(EntityTypeBuilder<CreditNoteLine> b){b.ToTable("credit_note_lines");b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasColumnName("id").HasConversion(x=>x.Value,x=>new CreditNoteLineId(x)).ValueGeneratedNever();b.Property(x=>x.CreditNoteId).HasColumnName("credit_note_id").HasConversion(x=>x.Value,x=>new CreditNoteId(x));b.Property(x=>x.InvoiceLineId).HasColumnName("invoice_line_id").HasConversion(x=>x.HasValue?x.Value.Value:(Guid?)null,x=>x.HasValue?new InvoiceLineId(x.Value):null);b.Property(x=>x.Description).HasColumnName("description").HasMaxLength(500);b.Property(x=>x.Quantity).HasColumnName("quantity").HasPrecision(18,4);b.Property(x=>x.Unit).HasColumnName("unit").HasMaxLength(50);b.Property(x=>x.UnitPrice).HasColumnName("unit_price").HasPrecision(18,2);b.Property(x=>x.DiscountAmount).HasColumnName("discount_amount").HasPrecision(18,2);b.Property(x=>x.TaxRate).HasColumnName("tax_rate").HasPrecision(9,4);b.Property(x=>x.NetAmount).HasColumnName("net_amount").HasPrecision(18,2);b.Property(x=>x.TaxAmount).HasColumnName("tax_amount").HasPrecision(18,2);b.Property(x=>x.TotalAmount).HasColumnName("total_amount").HasPrecision(18,2);}
}
