using DriveOS.SharedKernel.Domain;using DriveOS.SharedKernel.Identifiers;
namespace DriveOS.Modules.CurriculumPedagogy.Domain.Curricula.Events;
public sealed record CurriculumVersionSupersededDomainEvent(CurriculumId CurriculumId,OrganizationId OrganizationId,CurriculumVersionId VersionId,CurriculumVersionId ReplacedByVersionId,DateOnly EffectiveTo,DateTimeOffset CurriculumVersionSupersededAtUtc) :DomainEvent;
