// <auto-generated />
using System;
using DriveOS.Modules.CRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveOS.Modules.CRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260810200726_AddCrmTasks")]
    partial class AddCrmTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveOS.Modules.CRM.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedAdvisorId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_advisor_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_leads_organization_id");

                    b.HasIndex("OrganizationId", "BranchId")
                        .HasDatabaseName("ix_leads_organization_branch");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_leads_organization_status");

                    b.ToTable("leads", "crm");
                });

            modelBuilder.Entity("DriveOS.Modules.CRM.Domain.Tasks.CrmTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "LeadId", "Status")
                        .HasDatabaseName("ix_tasks_organization_lead_status");

                    b.HasIndex("OrganizationId", "Status", "DueAtUtc")
                        .HasDatabaseName("ix_tasks_organization_status_due");

                    b.ToTable("tasks", "crm");
                });

            modelBuilder.Entity("DriveOS.Modules.CRM.Domain.Leads.Lead", b =>
                {
                    b.OwnsOne("DriveOS.Modules.CRM.Domain.Leads.LeadIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("phone");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("DriveOS.Modules.CRM.Domain.Leads.LeadQualification", "Qualification", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Availability")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("qualification_availability");

                            b1.Property<string>("Financing")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("qualification_financing");

                            b1.Property<string>("LicenseCategory")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("qualification_license_category");

                            b1.Property<string>("Need")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("qualification_need");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("qualification_notes");

                            b1.Property<DateOnly?>("TargetDate")
                                .HasColumnType("date")
                                .HasColumnName("qualification_target_date");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("DriveOS.Modules.CRM.Domain.Leads.LeadSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Detail")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("source_detail");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("source_type");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("DriveOS.Modules.CRM.Domain.Leads.RequestedTraining", "RequestedTraining", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LicenseCategory")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("requested_license_category");

                            b1.Property<string>("PreferredLocation")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("preferred_location");

                            b1.Property<string>("Transmission")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("preferred_transmission");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("RequestedTraining")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
