// <auto-generated />
using System;
using DriveOS.Modules.Organizations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveOS.Modules.Organizations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260729141025_AddBranchStatusHistory")]
    partial class AddBranchStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("branch_type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_code");

                    b.HasIndex("OrganizationId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_primary_per_organization")
                        .HasFilter("is_primary = true AND status <> 'Closed'");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_normalized_name");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_branches_organization_status");

                    b.ToTable("branches", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.BranchStatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "ChangedAtUtc")
                        .HasDatabaseName("ix_branch_status_history_branch_date");

                    b.ToTable("branch_status_history", "organizations");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organization_type");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "LegalName")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_country_legal_name");

                    b.ToTable("organizations", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.OrganizationStatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ChangedAtUtc")
                        .HasDatabaseName("ix_organization_status_history_org_date");

                    b.ToTable("organization_status_history", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.Branch", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.Branches.BranchAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("country_code")
                                .IsFixedLength();

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.HasKey("BranchId");

                            b1.ToTable("branches", "organization");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.BranchStatusHistoryEntry", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Branches.Branch", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.OrganizationStatusHistoryEntry", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.Branch", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
