// <auto-generated />
using System;
using DriveOS.Modules.Organizations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveOS.Modules.Organizations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260806112703_FixeBug")]
    partial class FixeBug
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.BranchAssignments.BranchUserAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("assignment_type");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("EffectiveEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_end_at_utc");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("EndedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_user_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PlannedEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<Guid?>("SuspendedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("suspended_by_user_id");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("OrganizationId", "BranchId", "Status")
                        .HasDatabaseName("ix_branch_user_assignments_branch_status");

                    b.HasIndex("OrganizationId", "UserId", "AssignmentType")
                        .IsUnique()
                        .HasDatabaseName("ux_branch_user_assignments_primary_user")
                        .HasFilter("assignment_type = 'Primary' AND status <> 'Ended'");

                    b.HasIndex("OrganizationId", "UserId", "Status")
                        .HasDatabaseName("ix_branch_user_assignments_user_status");

                    b.HasIndex("OrganizationId", "BranchId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_branch_user_assignments_open_role")
                        .HasFilter("status <> 'Ended'");

                    b.ToTable("branch_user_assignments", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.BranchConfigurationOverrides.BranchConfigurationOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_configuration_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("BaseConfigurationId")
                        .HasDatabaseName("ix_branch_configuration_overrides_base_configuration");

                    b.HasIndex("BranchId");

                    b.HasIndex("OrganizationId", "BranchId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_branch_configuration_overrides_org_branch_version");

                    b.HasIndex("OrganizationId", "BranchId", "Status", "EffectiveFromUtc")
                        .HasDatabaseName("ix_branch_configuration_overrides_effective_resolution");

                    b.ToTable("branch_configuration_overrides", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("branch_type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_code");

                    b.HasIndex("OrganizationId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_primary_per_organization")
                        .HasFilter("is_primary = true AND status <> 'Closed'");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_normalized_name");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_branches_organization_status");

                    b.ToTable("branches", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.BranchManagerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("EndedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_user_id");

                    b.Property<Guid>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique()
                        .HasDatabaseName("ux_branch_manager_assignments_active_branch")
                        .HasFilter("status = 'Active' AND effective_to_utc IS NULL");

                    b.HasIndex("BranchId", "EffectiveFromUtc")
                        .HasDatabaseName("ix_branch_manager_assignments_branch_date");

                    b.HasIndex("BranchId", "Status")
                        .HasDatabaseName("ix_branch_manager_assignments_branch_status");

                    b.ToTable("branch_manager_assignments", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.BranchStatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "ChangedAtUtc")
                        .HasDatabaseName("ix_branch_status_history_branch_date");

                    b.ToTable("branch_status_history", "organizations");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationClosures.OrganizationClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DataDisposition")
                        .HasColumnType("integer")
                        .HasColumnName("data_disposition");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_comment");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("ReasonCode")
                        .HasColumnType("integer")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_details");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset>("RequestedEffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_effective_at_utc");

                    b.Property<DateTimeOffset?>("RetentionUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_until_utc");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_closures_open_per_org")
                        .HasFilter("status IN (1, 2, 3, 4)");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_organization_closures_org_status");

                    b.ToTable("organization_closures", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationConfigurations.OrganizationConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_configurations_organization_version");

                    b.HasIndex("OrganizationId", "Status", "EffectiveFromUtc")
                        .HasDatabaseName("ix_organization_configurations_effective_lookup");

                    b.ToTable("organization_configurations", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationLegalProfiles.OrganizationLegalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly?>("IncorporationDate")
                        .HasColumnType("date")
                        .HasColumnName("incorporation_date");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LegalForm")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("legal_form");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("registration_number");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_legal_profiles_organization");

                    b.HasIndex("RegistrationNumber", "Status")
                        .HasDatabaseName("ix_organization_legal_profiles_registration_status");

                    b.ToTable("organization_legal_profiles", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationRepresentatives.OrganizationRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsPrimaryOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_owner");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("RepresentativeType")
                        .HasColumnType("integer")
                        .HasColumnName("representative_type");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_representatives_primary_owner")
                        .HasFilter("is_primary_owner = TRUE AND status = 2");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_organization_representatives_org_status");

                    b.HasIndex("OrganizationId", "PersonId", "RepresentativeType")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_representatives_active_identity")
                        .HasFilter("status IN (1, 2, 3)");

                    b.ToTable("organization_representatives", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationSequences.OrganizationSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<int?>("LastResetMonth")
                        .HasColumnType("integer")
                        .HasColumnName("last_reset_month");

                    b.Property<int?>("LastResetYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_reset_year");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Padding")
                        .HasColumnType("integer")
                        .HasColumnName("padding");

                    b.Property<string>("ResetPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reset_policy");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_sequences_organization_code")
                        .HasFilter("branch_id IS NULL");

                    b.HasIndex("OrganizationId", "BranchId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_sequences_branch_code")
                        .HasFilter("branch_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "BranchId", "Status")
                        .HasDatabaseName("ix_organization_sequences_scope_status");

                    b.ToTable("organization_sequences", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_settings_organization_id");

                    b.ToTable("organization_settings", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organization_type");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "LegalName")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_country_legal_name");

                    b.ToTable("organizations", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.OrganizationStatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ChangedAtUtc")
                        .HasDatabaseName("ix_organization_status_history_org_date");

                    b.ToTable("organization_status_history", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Subscriptions.OrganizationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("external_provider");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("external_subscription_id");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_subscriptions_organization_id");

                    b.HasIndex("ExternalProvider", "ExternalSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_subscriptions_external_reference")
                        .HasFilter("external_provider IS NOT NULL AND external_subscription_id IS NOT NULL");

                    b.ToTable("organization_subscriptions", "organization");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.BranchAssignments.BranchUserAssignment", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.BranchConfigurationOverrides.BranchConfigurationOverride", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.OrganizationConfigurations.OrganizationConfiguration", null)
                        .WithMany()
                        .HasForeignKey("BaseConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriveOS.Modules.Organizations.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.BranchConfigurationOverrides.BranchOverridePayload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("BranchConfigurationOverrideId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("override_json");

                            b1.HasKey("BranchConfigurationOverrideId");

                            b1.ToTable("branch_configuration_overrides", "organization");

                            b1.WithOwner()
                                .HasForeignKey("BranchConfigurationOverrideId");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.Branch", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.Branches.BranchAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("country_code")
                                .IsFixedLength();

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.HasKey("BranchId");

                            b1.ToTable("branches", "organization");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.BranchManagerAssignment", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Branches.Branch", null)
                        .WithMany("ManagerAssignments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.BranchStatusHistoryEntry", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Branches.Branch", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationClosures.OrganizationClosure", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationConfigurations.OrganizationConfiguration", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationConfigurations.ConfigurationPayload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("OrganizationConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("settings_json");

                            b1.HasKey("OrganizationConfigurationId");

                            b1.ToTable("organization_configurations", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationConfigurationId");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationLegalProfiles.OrganizationLegalProfile", b =>
                {
                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationLegalProfiles.RegisteredAddress", "RegisteredAddress", b1 =>
                        {
                            b1.Property<Guid>("OrganizationLegalProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("registered_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("registered_country_code")
                                .IsFixedLength();

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("registered_address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("registered_address_line2");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("registered_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("registered_region");

                            b1.HasKey("OrganizationLegalProfileId");

                            b1.ToTable("organization_legal_profiles", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationLegalProfileId");
                        });

                    b.Navigation("RegisteredAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationRepresentatives.OrganizationRepresentative", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationRepresentatives.RepresentativeAuthorityScope", "AuthorityScope", b1 =>
                        {
                            b1.Property<Guid>("OrganizationRepresentativeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("authority_scope");

                            b1.HasKey("OrganizationRepresentativeId");

                            b1.ToTable("organization_representatives", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationRepresentativeId");
                        });

                    b.Navigation("AuthorityScope")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationSequences.OrganizationSequence", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationSequences.SequencePattern", "Pattern", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSequenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("pattern");

                            b1.HasKey("OrganizationSequenceId");

                            b1.ToTable("organization_sequences", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSequenceId");
                        });

                    b.Navigation("Pattern")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationSettings", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithOne()
                        .HasForeignKey("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("address_country_code")
                                .IsFixedLength();

                            b1.Property<string>("Line1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("region");

                            b1.HasKey("OrganizationSettingsId");

                            b1.ToTable("organization_settings", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSettingsId");
                        });

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationContactInformation", "Contact", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("contact_phone");

                            b1.Property<string>("Website")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("website");

                            b1.HasKey("OrganizationSettingsId");

                            b1.ToTable("organization_settings", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSettingsId");
                        });

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationOperationalSettings", "Operational", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowStudentSelfBooking")
                                .HasColumnType("boolean")
                                .HasColumnName("allow_student_self_booking");

                            b1.Property<int>("DefaultBookingLeadTimeMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("default_booking_lead_time_minutes");

                            b1.Property<Guid?>("DefaultBranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("default_branch_id");

                            b1.Property<int>("DefaultCancellationDelayHours")
                                .HasColumnType("integer")
                                .HasColumnName("default_cancellation_delay_hours");

                            b1.Property<int>("DefaultSessionDurationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("default_session_duration_minutes");

                            b1.Property<bool>("RequireBranchForOperations")
                                .HasColumnType("boolean")
                                .HasColumnName("require_branch_for_operations");

                            b1.HasKey("OrganizationSettingsId");

                            b1.ToTable("organization_settings", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSettingsId");
                        });

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("RegistrationNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("registration_number");

                            b1.Property<string>("TaxNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("tax_number");

                            b1.Property<string>("TradeName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("trade_name");

                            b1.HasKey("OrganizationSettingsId");

                            b1.ToTable("organization_settings", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSettingsId");
                        });

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.OrganizationSettings.OrganizationRegionalSettings", "Regional", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency_code")
                                .IsFixedLength();

                            b1.Property<string>("DateFormat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("date_format");

                            b1.Property<string>("DefaultLanguage")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("default_language");

                            b1.Property<string>("FirstDayOfWeek")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("first_day_of_week");

                            b1.Property<string>("MeasurementSystem")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("measurement_system");

                            b1.Property<string>("SupportedLanguages")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("supported_languages");

                            b1.Property<string>("TimeFormat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("time_format");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("time_zone_id");

                            b1.HasKey("OrganizationSettingsId");

                            b1.ToTable("organization_settings", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSettingsId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Operational")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Regional")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.OrganizationStatusHistoryEntry", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Subscriptions.OrganizationSubscription", b =>
                {
                    b.HasOne("DriveOS.Modules.Organizations.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.Subscriptions.SubscriptionPeriod", "CurrentPeriod", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("EndsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("current_period_ends_at_utc");

                            b1.Property<DateTimeOffset>("StartsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("current_period_starts_at_utc");

                            b1.HasKey("OrganizationSubscriptionId");

                            b1.ToTable("organization_subscriptions", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSubscriptionId");
                        });

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.Subscriptions.SubscriptionPeriod", "TrialPeriod", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("EndsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("trial_ends_at_utc");

                            b1.Property<DateTimeOffset>("StartsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("trial_starts_at_utc");

                            b1.HasKey("OrganizationSubscriptionId");

                            b1.ToTable("organization_subscriptions", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSubscriptionId");
                        });

                    b.OwnsOne("DriveOS.Modules.Organizations.Domain.Subscriptions.SubscriptionCancellation", "Cancellation", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EffectiveAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("cancellation_effective_at_utc");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("cancellation_reason");

                            b1.Property<DateTimeOffset>("RequestedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("cancellation_requested_at_utc");

                            b1.Property<Guid>("RequestedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("cancellation_requested_by_user_id");

                            b1.HasKey("OrganizationSubscriptionId");

                            b1.ToTable("organization_subscriptions", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSubscriptionId");
                        });

                    b.OwnsMany("DriveOS.Modules.Organizations.Domain.Subscriptions.SubscriptionEntitlement", "Entitlements", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSubscriptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("organization_subscription_id");

                            b1.Property<string>("Code")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("entitlement_code");

                            b1.HasKey("OrganizationSubscriptionId", "Code");

                            b1.ToTable("organization_subscription_entitlements", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSubscriptionId");
                        });

                    b.OwnsMany("DriveOS.Modules.Organizations.Domain.Subscriptions.SubscriptionLimit", "Limits", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSubscriptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("organization_subscription_id");

                            b1.Property<string>("Code")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("limit_code");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("limit_value");

                            b1.HasKey("OrganizationSubscriptionId", "Code");

                            b1.ToTable("organization_subscription_limits", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSubscriptionId");
                        });

                    b.Navigation("Cancellation");

                    b.Navigation("CurrentPeriod")
                        .IsRequired();

                    b.Navigation("Entitlements");

                    b.Navigation("Limits");

                    b.Navigation("TrialPeriod");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Branches.Branch", b =>
                {
                    b.Navigation("ManagerAssignments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("DriveOS.Modules.Organizations.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
