using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.Workforce.Application.Persistence;
using DriveOS.Modules.Workforce.Domain.Employees;
using DriveOS.Modules.Workforce.Domain.PerformanceReviews;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.Workforce.Application.PerformanceReviews;
public sealed class CreatePerformanceReviewCommandHandler(IPerformanceReviewRepository repo,IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<CreatePerformanceReviewCommand,PerformanceReviewId>{public async Task<Result<PerformanceReviewId>> Handle(CreatePerformanceReviewCommand c,CancellationToken ct){var e=await employees.GetByIdAsync(c.OrganizationId,c.EmployeeId,ct);if(e is null)return Result.Failure<PerformanceReviewId>(EmployeeErrors.NotFound);if(c.PeriodFrom<e.EmploymentStartDate||(e.EmploymentEndDate is DateOnly end&&c.PeriodTo>end))return Result.Failure<PerformanceReviewId>(PerformanceReviewErrors.InvalidPeriod);if(await repo.HasOverlapAsync(c.OrganizationId,c.EmployeeId,c.PeriodFrom,c.PeriodTo,null,ct))return Result.Failure<PerformanceReviewId>(PerformanceReviewErrors.OverlappingPeriod);var r=PerformanceReview.Create(c.Id,c.OrganizationId,c.EmployeeId,c.EvaluatorUserId,c.PeriodFrom,c.PeriodTo,c.Title,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return Result.Failure<PerformanceReviewId>(r.Error);repo.Add(r.Value);await uow.CommitAsync(ct);return Result.Success(r.Value.Id);}}
public sealed class GetPerformanceReviewQueryHandler(IPerformanceReviewRepository repo):IQueryHandler<GetPerformanceReviewQuery,PerformanceReviewResponse>{public async Task<Result<PerformanceReviewResponse>> Handle(GetPerformanceReviewQuery q,CancellationToken ct){var x=await repo.GetAsync(q.OrganizationId,q.Id,false,ct);return x is null?Result.Failure<PerformanceReviewResponse>(PerformanceReviewErrors.NotFound):Result.Success(Map(x));}internal static PerformanceReviewResponse Map(PerformanceReview x)=>new(x.Id.Value,x.EmployeeId.Value,x.EvaluatorUserId.Value,x.PeriodFrom,x.PeriodTo,x.Title,x.Status.ToString(),x.OverallAssessment,x.Objectives,x.SubmittedAtUtc,x.AcknowledgedAtUtc,x.AcknowledgedByUserId?.Value,x.EmployeeComment,x.CompletedAtUtc,x.CancellationReason,x.Criteria.OrderBy(c=>c.Code).Select(c=>new PerformanceReviewCriterionResponse(c.Id.Value,c.Code,c.Label,c.Weight,c.Rating,c.Comment)).ToArray());}
public sealed class GetPerformanceReviewsQueryHandler(IPerformanceReviewRepository repo):IQueryHandler<GetPerformanceReviewsQuery,IReadOnlyList<PerformanceReviewResponse>>{public async Task<Result<IReadOnlyList<PerformanceReviewResponse>>> Handle(GetPerformanceReviewsQuery q,CancellationToken ct)=>Result.Success<IReadOnlyList<PerformanceReviewResponse>>((await repo.ListAsync(q.OrganizationId,q.EmployeeId,q.Status,ct)).Select(GetPerformanceReviewQueryHandler.Map).ToArray());}
public abstract class ReviewCommandHandlerBase(IPerformanceReviewRepository repo,IWorkforceUnitOfWork uow,IClock clock){protected async Task<Result> Run(OrganizationId org,PerformanceReviewId id,UserId actor,Func<PerformanceReview,DateTimeOffset,UserId,Result> action,CancellationToken ct){var x=await repo.GetAsync(org,id,true,ct);if(x is null)return Result.Failure(PerformanceReviewErrors.NotFound);var r=action(x,clock.UtcNow,actor);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class StartPerformanceReviewCommandHandler(IPerformanceReviewRepository r,IWorkforceUnitOfWork u,IClock c):ReviewCommandHandlerBase(r,u,c),ICommandHandler<StartPerformanceReviewCommand>{public Task<Result> Handle(StartPerformanceReviewCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(a,n,u)=>a.Start(n,u),ct);}
public sealed class SetPerformanceReviewSummaryCommandHandler(IPerformanceReviewRepository r,IWorkforceUnitOfWork u,IClock c):ReviewCommandHandlerBase(r,u,c),ICommandHandler<SetPerformanceReviewSummaryCommand>{public Task<Result> Handle(SetPerformanceReviewSummaryCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(a,n,u)=>a.SetSummary(x.OverallAssessment,x.Objectives,n,u),ct);}
public sealed class SubmitPerformanceReviewCommandHandler(IPerformanceReviewRepository r,IWorkforceUnitOfWork u,IClock c):ReviewCommandHandlerBase(r,u,c),ICommandHandler<SubmitPerformanceReviewCommand>{public Task<Result> Handle(SubmitPerformanceReviewCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(a,n,u)=>a.Submit(n,u),ct);}
public sealed class AcknowledgePerformanceReviewCommandHandler(IPerformanceReviewRepository r,IWorkforceUnitOfWork u,IClock c):ReviewCommandHandlerBase(r,u,c),ICommandHandler<AcknowledgePerformanceReviewCommand>{public Task<Result> Handle(AcknowledgePerformanceReviewCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(a,n,u)=>a.Acknowledge(x.EmployeeComment,n,u),ct);}
public sealed class CompletePerformanceReviewCommandHandler(IPerformanceReviewRepository r,IWorkforceUnitOfWork u,IClock c):ReviewCommandHandlerBase(r,u,c),ICommandHandler<CompletePerformanceReviewCommand>{public Task<Result> Handle(CompletePerformanceReviewCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(a,n,u)=>a.Complete(n,u),ct);}
public sealed class CancelPerformanceReviewCommandHandler(IPerformanceReviewRepository r,IWorkforceUnitOfWork u,IClock c):ReviewCommandHandlerBase(r,u,c),ICommandHandler<CancelPerformanceReviewCommand>{public Task<Result> Handle(CancelPerformanceReviewCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(a,n,u)=>a.Cancel(x.Reason,n,u),ct);}
public sealed class AddPerformanceReviewCriterionCommandHandler(IPerformanceReviewRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<AddPerformanceReviewCriterionCommand,PerformanceReviewCriterionId>{public async Task<Result<PerformanceReviewCriterionId>> Handle(AddPerformanceReviewCriterionCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.ReviewId,true,ct);if(x is null)return Result.Failure<PerformanceReviewCriterionId>(PerformanceReviewErrors.NotFound);var r=x.AddCriterion(c.CriterionId,c.Code,c.Label,c.Weight,c.Comment,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return Result.Failure<PerformanceReviewCriterionId>(r.Error);await uow.CommitAsync(ct);return Result.Success(c.CriterionId);}}
public sealed class RatePerformanceReviewCriterionCommandHandler(IPerformanceReviewRepository repo,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<RatePerformanceReviewCriterionCommand>{public async Task<Result> Handle(RatePerformanceReviewCriterionCommand c,CancellationToken ct){var x=await repo.GetAsync(c.OrganizationId,c.ReviewId,true,ct);if(x is null)return Result.Failure(PerformanceReviewErrors.NotFound);var r=x.RateCriterion(c.CriterionId,c.Rating,c.Comment,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
