<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DomainRelay.Abstractions" />
    <PackageReference Include="DomainRelay.DependencyInjection" />
    <PackageReference Include="DomainRelay.Mapping" />
    <PackageReference Include="DomainRelay.Mapping.Abstractions" />
    <PackageReference Include="DomainRelay.Validation" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\DriveOS.Application.Abstractions\DriveOS.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DriveOS.SharedKernel\DriveOS.SharedKernel.csproj" />
    <ProjectReference Include="..\DriveOS.Modules.Organizations.Domain\DriveOS.Modules.Organizations.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
    <Folder Include="OrganizationSettings\" />
  </ItemGroup>
</Project>
