using DriveOS.Application.Abstractions.Messaging;
using DriveOS.Application.Abstractions.Time;
using DriveOS.Modules.Workforce.Application.Persistence;
using DriveOS.Modules.Workforce.Domain.EmployeeDocuments;
using DriveOS.Modules.Workforce.Domain.Employees;
using DriveOS.SharedKernel.Identifiers;
using DriveOS.SharedKernel.Results;
namespace DriveOS.Modules.Workforce.Application.EmployeeDocuments;
public sealed class RegisterEmployeeDocumentCommandHandler(IEmployeeDocumentRepository repo,IEmployeeRepository employees,IWorkforceUnitOfWork uow,IClock clock):ICommandHandler<RegisterEmployeeDocumentCommand,EmployeeDocumentId>{public async Task<Result<EmployeeDocumentId>> Handle(RegisterEmployeeDocumentCommand c,CancellationToken ct){if(await employees.GetByIdAsync(c.OrganizationId,c.EmployeeId,ct) is null)return Result.Failure<EmployeeDocumentId>(EmployeeErrors.NotFound);if(await repo.DocumentReferenceExistsAsync(c.OrganizationId,c.DocumentReferenceId,null,ct))return Result.Failure<EmployeeDocumentId>(EmployeeDocumentErrors.DuplicateDocumentReference);var r=EmployeeDocument.Create(c.Id,c.OrganizationId,c.EmployeeId,c.DocumentReferenceId,c.Category,c.DocumentTypeCode,c.Title,c.Confidentiality,c.IssuedOn,c.ValidFrom,c.ExpiresOn,c.Issuer,c.ReferenceNumber,clock.UtcNow,c.ActorUserId);if(r.IsFailure)return Result.Failure<EmployeeDocumentId>(r.Error);repo.Add(r.Value);await uow.CommitAsync(ct);return Result.Success(c.Id);}}
public sealed class GetEmployeeDocumentQueryHandler(IEmployeeDocumentRepository repo,IClock clock):IQueryHandler<GetEmployeeDocumentQuery,EmployeeDocumentResponse>{public async Task<Result<EmployeeDocumentResponse>> Handle(GetEmployeeDocumentQuery q,CancellationToken ct){var x=await repo.GetAsync(q.OrganizationId,q.Id,false,ct);return x is null?Result.Failure<EmployeeDocumentResponse>(EmployeeDocumentErrors.NotFound):Result.Success(Map(x,q.RevealReference,DateOnly.FromDateTime(clock.UtcNow.UtcDateTime)));}internal static EmployeeDocumentResponse Map(EmployeeDocument x,bool reveal,DateOnly today){bool protectedRef=x.Confidentiality is EmployeeDocumentConfidentiality.Confidential or EmployeeDocumentConfidentiality.Restricted;return new(x.Id.Value,x.EmployeeId.Value,!protectedRef||reveal?x.DocumentReferenceId:null,x.Category.ToString(),x.DocumentTypeCode,x.Title,x.Confidentiality.ToString(),x.IssuedOn,x.ValidFrom,x.ExpiresOn,x.IsExpired(today),x.Issuer,x.ReferenceNumber,x.Status.ToString(),x.VerifiedAtUtc,x.VerifiedByUserId?.Value,x.RevocationReason,x.SupersededByEmployeeDocumentId?.Value);}}
public sealed class GetEmployeeDocumentsQueryHandler(IEmployeeDocumentRepository repo,IClock clock):IQueryHandler<GetEmployeeDocumentsQuery,IReadOnlyList<EmployeeDocumentResponse>>{public async Task<Result<IReadOnlyList<EmployeeDocumentResponse>>> Handle(GetEmployeeDocumentsQuery q,CancellationToken ct){var today=DateOnly.FromDateTime(clock.UtcNow.UtcDateTime);return Result.Success<IReadOnlyList<EmployeeDocumentResponse>>((await repo.ListAsync(q.OrganizationId,q.EmployeeId,q.Category,q.Status,ct)).Select(x=>GetEmployeeDocumentQueryHandler.Map(x,q.RevealReferences,today)).ToArray());}}
public abstract class EmployeeDocumentCommandHandlerBase(IEmployeeDocumentRepository repo,IWorkforceUnitOfWork uow,IClock clock){protected async Task<Result> Run(OrganizationId org,EmployeeDocumentId id,UserId actor,Func<EmployeeDocument,DateTimeOffset,UserId,Result> action,CancellationToken ct){var x=await repo.GetAsync(org,id,true,ct);if(x is null)return Result.Failure(EmployeeDocumentErrors.NotFound);var r=action(x,clock.UtcNow,actor);if(r.IsFailure)return r;await uow.CommitAsync(ct);return Result.Success();}}
public sealed class UpdateEmployeeDocumentCommandHandler(IEmployeeDocumentRepository r,IWorkforceUnitOfWork u,IClock c):EmployeeDocumentCommandHandlerBase(r,u,c),ICommandHandler<UpdateEmployeeDocumentCommand>{public Task<Result> Handle(UpdateEmployeeDocumentCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(d,n,a)=>d.UpdateMetadata(x.Category,x.DocumentTypeCode,x.Title,x.Confidentiality,x.IssuedOn,x.ValidFrom,x.ExpiresOn,x.Issuer,x.ReferenceNumber,n,a),ct);}
public sealed class VerifyEmployeeDocumentCommandHandler(IEmployeeDocumentRepository r,IWorkforceUnitOfWork u,IClock c):EmployeeDocumentCommandHandlerBase(r,u,c),ICommandHandler<VerifyEmployeeDocumentCommand>{public Task<Result> Handle(VerifyEmployeeDocumentCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(d,n,a)=>d.Verify(n,a),ct);}
public sealed class SupersedeEmployeeDocumentCommandHandler(IEmployeeDocumentRepository r,IWorkforceUnitOfWork u,IClock c):EmployeeDocumentCommandHandlerBase(r,u,c),ICommandHandler<SupersedeEmployeeDocumentCommand>{public Task<Result> Handle(SupersedeEmployeeDocumentCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(d,n,a)=>d.Supersede(x.ReplacementId,n,a),ct);}
public sealed class RevokeEmployeeDocumentCommandHandler(IEmployeeDocumentRepository r,IWorkforceUnitOfWork u,IClock c):EmployeeDocumentCommandHandlerBase(r,u,c),ICommandHandler<RevokeEmployeeDocumentCommand>{public Task<Result> Handle(RevokeEmployeeDocumentCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(d,n,a)=>d.Revoke(x.Reason,n,a),ct);}
public sealed class ArchiveEmployeeDocumentCommandHandler(IEmployeeDocumentRepository r,IWorkforceUnitOfWork u,IClock c):EmployeeDocumentCommandHandlerBase(r,u,c),ICommandHandler<ArchiveEmployeeDocumentCommand>{public Task<Result> Handle(ArchiveEmployeeDocumentCommand x,CancellationToken ct)=>Run(x.OrganizationId,x.Id,x.ActorUserId,(d,n,a)=>d.Archive(n,a),ct);}
