using DriveOS.Modules.Students.Domain.Enrollments;using DriveOS.SharedKernel.Domain;using DriveOS.SharedKernel.Identifiers;using DriveOS.SharedKernel.Results;using DriveOS.Modules.Students.Domain.Events;
namespace DriveOS.Modules.Students.Domain.Closures;
public sealed class EnrollmentClosureCase:AggregateRoot<EnrollmentClosureCaseId>
{
 private readonly List<EnrollmentClosureCheck> checks=[];private EnrollmentClosureCase(){}
 private EnrollmentClosureCase(EnrollmentClosureCaseId id,OrganizationId org,PersonId student,DraftEnrollmentId enrollment,EnrollmentStatus previous,EnrollmentClosureReason reason,DateOnly closureDate,string detail,UserId actor,DateTimeOffset now):base(id){OrganizationId=org;StudentId=student;EnrollmentId=enrollment;PreviousEnrollmentStatus=previous;Reason=reason;ClosureDate=closureDate;ReasonDetail=detail;CreatedByUserId=actor;CreatedAtUtc=now;Status=EnrollmentClosureStatus.Draft;RaiseDomainEvent(new StudentAggregateChangedDomainEvent<EnrollmentClosureCaseId>(Id,StudentId,OrganizationId,"Created"));}
 public OrganizationId OrganizationId{get;private set;}public PersonId StudentId{get;private set;}public DraftEnrollmentId EnrollmentId{get;private set;}public EnrollmentStatus PreviousEnrollmentStatus{get;private set;}public EnrollmentClosureReason Reason{get;private set;}public DateOnly ClosureDate{get;private set;}public string ReasonDetail{get;private set;}=string.Empty;public EnrollmentClosureStatus Status{get;private set;}public Guid? OperationalBlockId{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public UserId CreatedByUserId{get;private set;}public DateTimeOffset? ClosedAtUtc{get;private set;}public UserId? ClosedByUserId{get;private set;}public DateTimeOffset? ArchivedAtUtc{get;private set;}public UserId? ArchivedByUserId{get;private set;}public DateOnly? RetainUntil{get;private set;}public string? RetentionLegalBasis{get;private set;}public StudentDataRetentionScope RetentionScope{get;private set;}public DateTimeOffset? ReopenedAtUtc{get;private set;}public UserId? ReopenedByUserId{get;private set;}public string? ReopenJustification{get;private set;}public IReadOnlyCollection<EnrollmentClosureCheck> Checks=>checks;
 public static Result<EnrollmentClosureCase>Create(OrganizationId org,PersonId student,DraftEnrollmentId enrollment,EnrollmentStatus previous,EnrollmentClosureReason reason,DateOnly closureDate,string detail,UserId actor,DateTimeOffset now,IReadOnlyList<EnrollmentClosureCheckSeed> seeds){if(org.IsEmpty||student.IsEmpty||enrollment.IsEmpty)return Result.Failure<EnrollmentClosureCase>(EnrollmentClosureErrors.InvalidOwner);detail=detail?.Trim()??string.Empty;if(reason==EnrollmentClosureReason.Other&&detail.Length==0||detail.Length>2000)return Result.Failure<EnrollmentClosureCase>(EnrollmentClosureErrors.InvalidReason);if(closureDate<DateOnly.FromDateTime(now.UtcDateTime))return Result.Failure<EnrollmentClosureCase>(EnrollmentClosureErrors.InvalidDate);var expected=Enum.GetValues<EnrollmentClosureCheckType>();if(seeds.Count!=expected.Length||seeds.Select(x=>x.Type).Distinct().Count()!=expected.Length||expected.Any(x=>seeds.All(y=>y.Type!=x))||seeds.Any(x=>!Enum.IsDefined(x.Status)||(x.Detail?.Trim().Length??0)>1000))return Result.Failure<EnrollmentClosureCase>(EnrollmentClosureErrors.InvalidChecks);var x=new EnrollmentClosureCase(EnrollmentClosureCaseId.New(),org,student,enrollment,previous,reason,closureDate,detail,actor,now);foreach(var s in seeds)x.checks.Add(EnrollmentClosureCheck.Create(x.Id,s));x.RefreshReadiness();return Result.Success(x);}
 public Result ReviewCheck(EnrollmentClosureCheckType type,EnrollmentClosureCheckStatus status,string detail){if(Status is EnrollmentClosureStatus.Closed or EnrollmentClosureStatus.Archived or EnrollmentClosureStatus.Reopened or EnrollmentClosureStatus.Cancelled)return Result.Failure(EnrollmentClosureErrors.InvalidTransition);detail=detail?.Trim()??string.Empty;if(!Enum.IsDefined(status)||detail.Length>1000)return Result.Failure(EnrollmentClosureErrors.InvalidChecks);var c=checks.SingleOrDefault(x=>x.Type==type);if(c is null)return Result.Failure(EnrollmentClosureErrors.InvalidChecks);c.Review(status,detail);RefreshReadiness();return Result.Success();}
 public Result Close(Guid blockId,UserId actor,DateTimeOffset now){if(ClosureDate>DateOnly.FromDateTime(now.UtcDateTime))return Result.Failure(EnrollmentClosureErrors.InvalidDate);if(Status!=EnrollmentClosureStatus.ReadyToClose||checks.Any(x=>x.Status is not (EnrollmentClosureCheckStatus.Resolved or EnrollmentClosureCheckStatus.NotApplicable)))return Result.Failure(EnrollmentClosureErrors.PreconditionsNotResolved);if(blockId==Guid.Empty)return Result.Failure(EnrollmentClosureErrors.InvalidOwner);OperationalBlockId=blockId;Status=EnrollmentClosureStatus.Closed;ClosedAtUtc=now;ClosedByUserId=actor;RaiseDomainEvent(new StudentAggregateChangedDomainEvent<EnrollmentClosureCaseId>(Id,StudentId,OrganizationId,"Closed"));return Result.Success();}
 public Result Archive(DateOnly retainUntil,string legalBasis,StudentDataRetentionScope scope,UserId actor,DateTimeOffset now){if(Status!=EnrollmentClosureStatus.Closed)return Result.Failure(EnrollmentClosureErrors.InvalidTransition);legalBasis=legalBasis?.Trim()??string.Empty;if(retainUntil<=DateOnly.FromDateTime(now.UtcDateTime)||legalBasis.Length is 0 or >1000||scope==StudentDataRetentionScope.None)return Result.Failure(EnrollmentClosureErrors.RetentionRequired);RetainUntil=retainUntil;RetentionLegalBasis=legalBasis;RetentionScope=scope;Status=EnrollmentClosureStatus.Archived;ArchivedAtUtc=now;ArchivedByUserId=actor;RaiseDomainEvent(new StudentAggregateChangedDomainEvent<EnrollmentClosureCaseId>(Id,StudentId,OrganizationId,"Archived"));return Result.Success();}
 public Result Reopen(string justification,UserId actor,DateTimeOffset now){justification=justification?.Trim()??string.Empty;if(Status is not (EnrollmentClosureStatus.Closed or EnrollmentClosureStatus.Archived))return Result.Failure(EnrollmentClosureErrors.InvalidTransition);if(justification.Length is < 10 or > 2000)return Result.Failure(EnrollmentClosureErrors.ReopenJustificationRequired);Status=EnrollmentClosureStatus.Reopened;ReopenJustification=justification;ReopenedAtUtc=now;ReopenedByUserId=actor;RaiseDomainEvent(new StudentAggregateChangedDomainEvent<EnrollmentClosureCaseId>(Id,StudentId,OrganizationId,"Reopened"));return Result.Success();}
 private void RefreshReadiness()=>Status=checks.All(x=>x.Status is EnrollmentClosureCheckStatus.Resolved or EnrollmentClosureCheckStatus.NotApplicable)?EnrollmentClosureStatus.ReadyToClose:EnrollmentClosureStatus.Draft;
}
public sealed class EnrollmentClosureCheck{private EnrollmentClosureCheck(){}public Guid Id{get;private set;}public EnrollmentClosureCaseId EnrollmentClosureCaseId{get;private set;}public EnrollmentClosureCheckType Type{get;private set;}public EnrollmentClosureCheckStatus Status{get;private set;}public string Detail{get;private set;}=string.Empty;internal static EnrollmentClosureCheck Create(EnrollmentClosureCaseId parent,EnrollmentClosureCheckSeed seed)=>new(){Id=Guid.NewGuid(),EnrollmentClosureCaseId=parent,Type=seed.Type,Status=seed.Status,Detail=(seed.Detail??string.Empty).Trim()};internal void Review(EnrollmentClosureCheckStatus status,string detail){Status=status;Detail=(detail??string.Empty).Trim();}}
