using DomainRelay.Abstractions;using DriveOS.Application.Abstractions.Authentication;
using DriveOS.Modules.Workforce.Application.EmployeeDocuments;
using DriveOS.Modules.Workforce.Domain.EmployeeDocuments;
using DriveOS.SharedKernel.Identifiers;using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.Workforce;
internal static class EmployeeDocumentEndpoints
{
 internal static IEndpointRouteBuilder MapEmployeeDocumentEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/workforce/employee-documents").WithTags("Workforce - Employee Documents");g.MapGet("/",List).RequireAuthorization("Workforce.EmployeeDocuments.Read");g.MapGet("/{id:guid}",Get).RequireAuthorization("Workforce.EmployeeDocuments.Read");g.MapGet("/{id:guid}/reference",GetReference).RequireAuthorization("Workforce.EmployeeDocuments.Confidential.Read");g.MapPost("/",Create).RequireAuthorization("Workforce.EmployeeDocuments.Manage");g.MapPut("/{id:guid}",Update).RequireAuthorization("Workforce.EmployeeDocuments.Manage");g.MapPost("/{id:guid}/verify",Verify).RequireAuthorization("Workforce.EmployeeDocuments.Verify");g.MapPost("/{id:guid}/supersede",Supersede).RequireAuthorization("Workforce.EmployeeDocuments.Manage");g.MapPost("/{id:guid}/revoke",Revoke).RequireAuthorization("Workforce.EmployeeDocuments.Manage");g.MapPost("/{id:guid}/archive",Archive).RequireAuthorization("Workforce.EmployeeDocuments.Manage");return app;}
 static async Task<IResult> List(Guid? employeeId,EmployeeDocumentCategory? category,EmployeeDocumentStatus? status,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetEmployeeDocumentsQuery(o,employeeId.HasValue?new EmployeeId(employeeId.Value):null,category,status,false),ct);return r.IsSuccess?Results.Ok(r.Value):P(r.Error);}
 static async Task<IResult> Get(Guid id,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetEmployeeDocumentQuery(o,new(id),false),ct);return r.IsSuccess?Results.Ok(r.Value):P(r.Error);}
 static async Task<IResult> GetReference(Guid id,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetEmployeeDocumentQuery(o,new(id),true),ct);return r.IsSuccess?Results.Ok(new{id=r.Value.Id,documentReferenceId=r.Value.DocumentReferenceId}):P(r.Error);}
 static async Task<IResult> Create(RegisterRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var id=EmployeeDocumentId.New();var r=await m.Send(new RegisterEmployeeDocumentCommand(o,id,new(q.EmployeeId),q.DocumentReferenceId,q.Category,q.DocumentTypeCode,q.Title,q.Confidentiality,q.IssuedOn,q.ValidFrom,q.ExpiresOn,q.Issuer,q.ReferenceNumber,a),ct);return r.IsSuccess?Results.Created($"/api/workforce/employee-documents/{id.Value}",new{id=id.Value}):P(r.Error);}
 static async Task<IResult> Update(Guid id,UpdateRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new UpdateEmployeeDocumentCommand(o,new(id),q.Category,q.DocumentTypeCode,q.Title,q.Confidentiality,q.IssuedOn,q.ValidFrom,q.ExpiresOn,q.Issuer,q.ReferenceNumber,a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static Task<IResult> Verify(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct)=>Send(id,m,t,u,(o,x,a)=>new VerifyEmployeeDocumentCommand(o,x,a),ct);
 static async Task<IResult> Supersede(Guid id,SupersedeRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new SupersedeEmployeeDocumentCommand(o,new(id),new(q.ReplacementEmployeeDocumentId),a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static async Task<IResult> Revoke(Guid id,RevokeRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new RevokeEmployeeDocumentCommand(o,new(id),q.Reason,a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static Task<IResult> Archive(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct)=>Send(id,m,t,u,(o,x,a)=>new ArchiveEmployeeDocumentCommand(o,x,a),ct);
 static async Task<IResult> Send<T>(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,Func<OrganizationId,EmployeeDocumentId,UserId,T> f,CancellationToken ct) where T:DriveOS.Application.Abstractions.Messaging.ICommand{if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(f(o,new(id),a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static IResult P(Error e)=>Results.Problem(statusCode:e.Type switch{ErrorType.NotFound=>404,ErrorType.Conflict=>409,ErrorType.Validation=>400,_=>400},extensions:new Dictionary<string,object?>{{"code",e.Code},{"messageKey",e.MessageKey}});
 public sealed record RegisterRequest(Guid EmployeeId,Guid DocumentReferenceId,EmployeeDocumentCategory Category,string DocumentTypeCode,string Title,EmployeeDocumentConfidentiality Confidentiality,DateOnly? IssuedOn,DateOnly? ValidFrom,DateOnly? ExpiresOn,string? Issuer,string? ReferenceNumber);
 public sealed record UpdateRequest(EmployeeDocumentCategory Category,string DocumentTypeCode,string Title,EmployeeDocumentConfidentiality Confidentiality,DateOnly? IssuedOn,DateOnly? ValidFrom,DateOnly? ExpiresOn,string? Issuer,string? ReferenceNumber);
 public sealed record SupersedeRequest(Guid ReplacementEmployeeDocumentId);public sealed record RevokeRequest(string Reason);
}
