using DomainRelay.Abstractions; using DriveOS.Application.Abstractions.Authentication; using DriveOS.Modules.Workforce.Application.EquipmentAssignments; using DriveOS.Modules.Workforce.Domain.EquipmentAssignments; using DriveOS.SharedKernel.Identifiers; using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.Workforce;
internal static class EquipmentAssignmentEndpoints
{
 internal static IEndpointRouteBuilder MapEquipmentAssignmentEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/workforce/equipment-assignments").WithTags("Workforce - Equipment Assignments");g.MapGet("/",List).RequireAuthorization("Workforce.EquipmentAssignments.Read");g.MapGet("/{id:guid}",Get).RequireAuthorization("Workforce.EquipmentAssignments.Read");g.MapPost("/",Create).RequireAuthorization("Workforce.EquipmentAssignments.Manage");g.MapPut("/{id:guid}",Update).RequireAuthorization("Workforce.EquipmentAssignments.Manage");g.MapPost("/{id:guid}/handover",HandOver).RequireAuthorization("Workforce.EquipmentAssignments.Manage");g.MapPost("/{id:guid}/return",Return).RequireAuthorization("Workforce.EquipmentAssignments.Manage");g.MapPost("/{id:guid}/cancel",Cancel).RequireAuthorization("Workforce.EquipmentAssignments.Manage");return app;}
 static async Task<IResult> List(Guid? employeeId,EquipmentAssignmentStatus? status,EquipmentResourceType? resourceType,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetEquipmentAssignmentsQuery(o,employeeId.HasValue?new EmployeeId(employeeId.Value):null,status,resourceType),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> Get(Guid id,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetEquipmentAssignmentQuery(o,new EquipmentAssignmentId(id)),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> Create(CreateEquipmentAssignmentRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var id=q.Id is{}x&&x!=Guid.Empty?new EquipmentAssignmentId(x):EquipmentAssignmentId.New();var r=await m.Send(new CreateEquipmentAssignmentCommand(o,id,new EmployeeId(q.EmployeeId),q.ResourceType,q.ResourceId,q.StartDate,q.PlannedEndDate,a),ct);return r.IsSuccess?Results.Created($"/api/workforce/equipment-assignments/{r.Value.Value}",new{id=r.Value.Value}):Problem(r.Error);}
 static async Task<IResult> Update(Guid id,UpdateEquipmentAssignmentRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new UpdateEquipmentAssignmentPlanCommand(o,new EquipmentAssignmentId(id),q.StartDate,q.PlannedEndDate,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> HandOver(Guid id,EquipmentConditionRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new HandOverEquipmentAssignmentCommand(o,new EquipmentAssignmentId(id),q.Condition,q.Notes,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Return(Guid id,ReturnEquipmentRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new ReturnEquipmentAssignmentCommand(o,new EquipmentAssignmentId(id),q.ReturnedOn,q.Condition,q.Notes,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Cancel(Guid id,CancelEquipmentAssignmentRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new CancelEquipmentAssignmentCommand(o,new EquipmentAssignmentId(id),q.Reason,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static IResult Problem(Error e)=>Results.Problem(statusCode:e.Type switch{ErrorType.NotFound=>404,ErrorType.Conflict=>409,ErrorType.Validation=>400,_=>400},extensions:new Dictionary<string,object?>{{"code",e.Code},{"messageKey",e.MessageKey}});
}
public sealed record CreateEquipmentAssignmentRequest(Guid? Id,Guid EmployeeId,EquipmentResourceType ResourceType,Guid ResourceId,DateOnly StartDate,DateOnly? PlannedEndDate);
public sealed record UpdateEquipmentAssignmentRequest(DateOnly StartDate,DateOnly? PlannedEndDate);
public sealed record EquipmentConditionRequest(EquipmentCondition Condition,string? Notes);
public sealed record ReturnEquipmentRequest(DateOnly ReturnedOn,EquipmentCondition Condition,string? Notes);
public sealed record CancelEquipmentAssignmentRequest(string Reason);
