using DomainRelay.Abstractions; using DriveOS.Application.Abstractions.Authentication; using DriveOS.Modules.Workforce.Application.LeavePolicies; using DriveOS.Modules.Workforce.Domain.LeavePolicies; using DriveOS.SharedKernel.Identifiers; using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.Workforce;
internal static class LeavePolicyEndpoints
{
 internal static IEndpointRouteBuilder MapLeavePolicyEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/workforce/leave-policies").WithTags("Workforce - Leave Policies");g.MapGet("/",GetAll).RequireAuthorization("Workforce.LeavePolicies.Read");g.MapGet("/{id:guid}",GetOne).RequireAuthorization("Workforce.LeavePolicies.Read");g.MapPost("/",Create).RequireAuthorization("Workforce.LeavePolicies.Manage");g.MapPut("/{id:guid}",Update).RequireAuthorization("Workforce.LeavePolicies.Manage");g.MapPost("/{id:guid}/deactivate",Deactivate).RequireAuthorization("Workforce.LeavePolicies.Manage");g.MapPost("/{id:guid}/reactivate",Reactivate).RequireAuthorization("Workforce.LeavePolicies.Manage");return app;}
 static async Task<IResult> GetAll(string? countryCode,string? status,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();LeavePolicyStatus? st=null;if(!string.IsNullOrWhiteSpace(status)){if(!Enum.TryParse<LeavePolicyStatus>(status,true,out var x))return Results.BadRequest(new{code="Workforce.LeavePolicy.InvalidStatus",messageKey="errors.workforce.leavePolicy.invalidStatus"});st=x;}var r=await m.Send(new GetLeavePoliciesQuery(o,countryCode,st),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> GetOne(Guid id,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetLeavePolicyQuery(o,new LeavePolicyId(id)),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> Create(LeavePolicyRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();if(!Enum.TryParse<LeaveCategory>(q.Category,true,out var c))return Results.BadRequest(new{code="Workforce.LeavePolicy.InvalidCategory",messageKey="errors.workforce.leavePolicy.invalidCategory"});var id=q.Id is{}x&&x!=Guid.Empty?new LeavePolicyId(x):LeavePolicyId.New();var r=await m.Send(new CreateLeavePolicyCommand(o,id,q.CountryCode,q.Code,q.Name,c,q.IsPaid,q.RequiresApproval,q.RequiresEvidence,q.AllowHalfDay,q.MinimumNoticeDays,q.MaximumConsecutiveDays,a),ct);return r.IsSuccess?Results.Created($"/api/workforce/leave-policies/{r.Value.Value}",new{id=r.Value.Value}):Problem(r.Error);}
 static async Task<IResult> Update(Guid id,LeavePolicyRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();if(!Enum.TryParse<LeaveCategory>(q.Category,true,out var c))return Results.BadRequest(new{code="Workforce.LeavePolicy.InvalidCategory",messageKey="errors.workforce.leavePolicy.invalidCategory"});var r=await m.Send(new UpdateLeavePolicyCommand(o,new LeavePolicyId(id),q.CountryCode,q.Code,q.Name,c,q.IsPaid,q.RequiresApproval,q.RequiresEvidence,q.AllowHalfDay,q.MinimumNoticeDays,q.MaximumConsecutiveDays,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Deactivate(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new DeactivateLeavePolicyCommand(o,new LeavePolicyId(id),a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Reactivate(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new ReactivateLeavePolicyCommand(o,new LeavePolicyId(id),a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static IResult Problem(Error e)=>Results.Problem(statusCode:e.Type switch{ErrorType.NotFound=>404,ErrorType.Conflict=>409,ErrorType.Validation=>400,_=>400},extensions:new Dictionary<string,object?>{{"code",e.Code},{"messageKey",e.MessageKey}});
}
public sealed record LeavePolicyRequest(Guid? Id,string CountryCode,string Code,string Name,string Category,bool IsPaid,bool RequiresApproval,bool RequiresEvidence,bool AllowHalfDay,int? MinimumNoticeDays,int? MaximumConsecutiveDays);
