using DomainRelay.Abstractions;using DriveOS.Application.Abstractions.Authentication;using DriveOS.Modules.Workforce.Application.ProfessionalRestrictions;using DriveOS.Modules.Workforce.Domain.ProfessionalRestrictions;using DriveOS.SharedKernel.Identifiers;using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.Workforce;
internal static class ProfessionalRestrictionEndpoints
{
 internal static IEndpointRouteBuilder MapProfessionalRestrictionEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/workforce/professional-restrictions").WithTags("Workforce - Professional Restrictions");g.MapGet("/",List).RequireAuthorization("Workforce.ProfessionalRestrictions.Read");g.MapGet("/{id:guid}",Get).RequireAuthorization("Workforce.ProfessionalRestrictions.Read");g.MapPost("/",Create).RequireAuthorization("Workforce.ProfessionalRestrictions.Manage");g.MapPut("/{id:guid}",Update).RequireAuthorization("Workforce.ProfessionalRestrictions.Manage");g.MapPost("/{id:guid}/activate",Activate).RequireAuthorization("Workforce.ProfessionalRestrictions.Apply");g.MapPost("/{id:guid}/lift",Lift).RequireAuthorization("Workforce.ProfessionalRestrictions.Lift");g.MapPost("/{id:guid}/cancel",Cancel).RequireAuthorization("Workforce.ProfessionalRestrictions.Manage");return app;}
 static async Task<IResult> List(Guid? employeeId,ProfessionalRestrictionStatus? status,ProfessionalRestrictionActivity? activity,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetProfessionalRestrictionsQuery(o,employeeId.HasValue?new EmployeeId(employeeId.Value):null,status,activity),ct);return r.IsSuccess?Results.Ok(r.Value):P(r.Error);}
 static async Task<IResult> Get(Guid id,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetProfessionalRestrictionQuery(o,new(id)),ct);return r.IsSuccess?Results.Ok(r.Value):P(r.Error);}
 static async Task<IResult> Create(CreateRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var id=ProfessionalRestrictionId.New();var r=await m.Send(new CreateProfessionalRestrictionCommand(o,id,new(q.EmployeeId),q.Activity,q.Source,q.StartDate,q.EndDate,q.Reason,q.CountryCode,q.LicenseCategoryCode,q.BranchId.HasValue?new BranchId(q.BranchId.Value):null,q.SupportingDocumentReferenceId,a),ct);return r.IsSuccess?Results.Created($"/api/workforce/professional-restrictions/{id.Value}",new{id=id.Value}):P(r.Error);}
 static async Task<IResult> Update(Guid id,UpdateRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new UpdateProfessionalRestrictionCommand(o,new(id),q.StartDate,q.EndDate,q.Reason,q.CountryCode,q.LicenseCategoryCode,q.BranchId.HasValue?new BranchId(q.BranchId.Value):null,q.SupportingDocumentReferenceId,a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static Task<IResult> Activate(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct)=>Send(id,m,t,u,(o,x,a)=>new ActivateProfessionalRestrictionCommand(o,x,a),ct);
 static async Task<IResult> Lift(Guid id,ReasonRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new LiftProfessionalRestrictionCommand(o,new(id),q.Reason,a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static async Task<IResult> Cancel(Guid id,ReasonRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new CancelProfessionalRestrictionCommand(o,new(id),q.Reason,a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static async Task<IResult> Send<T>(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,Func<OrganizationId,ProfessionalRestrictionId,UserId,T> f,CancellationToken ct) where T:DriveOS.Application.Abstractions.Messaging.ICommand{if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(f(o,new(id),a),ct);return r.IsSuccess?Results.NoContent():P(r.Error);}
 static IResult P(Error e)=>Results.Problem(statusCode:e.Type switch{ErrorType.NotFound=>404,ErrorType.Conflict=>409,ErrorType.Validation=>400,_=>400},extensions:new Dictionary<string,object?>{{"code",e.Code},{"messageKey",e.MessageKey}});
 public sealed record CreateRequest(Guid EmployeeId,ProfessionalRestrictionActivity Activity,ProfessionalRestrictionSource Source,DateOnly StartDate,DateOnly? EndDate,string Reason,string? CountryCode,string? LicenseCategoryCode,Guid? BranchId,Guid? SupportingDocumentReferenceId);
 public sealed record UpdateRequest(DateOnly StartDate,DateOnly? EndDate,string Reason,string? CountryCode,string? LicenseCategoryCode,Guid? BranchId,Guid? SupportingDocumentReferenceId);public sealed record ReasonRequest(string Reason);
}
