using DomainRelay.Abstractions; using DriveOS.Application.Abstractions.Authentication; using DriveOS.Modules.Workforce.Application.Timesheets; using DriveOS.Modules.Workforce.Domain.Timesheets; using DriveOS.SharedKernel.Identifiers; using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.Workforce;
internal static class TimesheetEndpoints
{
 internal static IEndpointRouteBuilder MapTimesheetEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/workforce/timesheets").WithTags("Workforce - Timesheets");g.MapGet("/",List).RequireAuthorization("Workforce.Timesheets.Read");g.MapGet("/{id:guid}",Get).RequireAuthorization("Workforce.Timesheets.Read");g.MapPost("/",Create).RequireAuthorization("Workforce.Timesheets.Manage");g.MapPost("/{id:guid}/entries",AddEntry).RequireAuthorization("Workforce.Timesheets.Manage");g.MapPut("/{id:guid}/entries/{entryId:guid}",UpdateEntry).RequireAuthorization("Workforce.Timesheets.Manage");g.MapDelete("/{id:guid}/entries/{entryId:guid}",RemoveEntry).RequireAuthorization("Workforce.Timesheets.Manage");g.MapPost("/{id:guid}/submit",Submit).RequireAuthorization("Workforce.Timesheets.Submit");g.MapPost("/{id:guid}/review/start",StartReview).RequireAuthorization("Workforce.Timesheets.Approve");g.MapPost("/{id:guid}/approve",Approve).RequireAuthorization("Workforce.Timesheets.Approve");g.MapPost("/{id:guid}/reject",Reject).RequireAuthorization("Workforce.Timesheets.Approve");g.MapPost("/{id:guid}/lock",Lock).RequireAuthorization("Workforce.Timesheets.Lock");return app;}
 static async Task<IResult> List(Guid? employeeId,TimesheetStatus? status,DateOnly? from,DateOnly? to,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetTimesheetsQuery(o,employeeId.HasValue?new EmployeeId(employeeId.Value):null,status,from,to),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> Get(Guid id,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetTimesheetQuery(o,new TimesheetId(id)),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> Create(CreateTimesheetRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var id=q.Id is{}x&&x!=Guid.Empty?new TimesheetId(x):TimesheetId.New();var r=await m.Send(new CreateTimesheetCommand(o,id,new EmployeeId(q.EmployeeId),q.PeriodFrom,q.PeriodTo,a),ct);return r.IsSuccess?Results.Created($"/api/workforce/timesheets/{r.Value.Value}",new{id=r.Value.Value}):Problem(r.Error);}
 static async Task<IResult> AddEntry(Guid id,TimesheetEntryRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var eid=q.Id is{}x&&x!=Guid.Empty?new TimesheetEntryId(x):TimesheetEntryId.New();var r=await m.Send(new AddTimesheetEntryCommand(o,new TimesheetId(id),eid,q.Date,q.ActivityType,q.Hours,q.Description,q.Source,q.SourceReference,a),ct);return r.IsSuccess?Results.Ok(new{id=r.Value.Value}):Problem(r.Error);}
 static async Task<IResult> UpdateEntry(Guid id,Guid entryId,TimesheetEntryRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new UpdateTimesheetEntryCommand(o,new TimesheetId(id),new TimesheetEntryId(entryId),q.Date,q.ActivityType,q.Hours,q.Description,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> RemoveEntry(Guid id,Guid entryId,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new RemoveTimesheetEntryCommand(o,new TimesheetId(id),new TimesheetEntryId(entryId),a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static Task<IResult> Submit(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct)=>Send(id,m,t,u,(o,x,a)=>new SubmitTimesheetCommand(o,x,a),ct);
 static Task<IResult> StartReview(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct)=>Send(id,m,t,u,(o,x,a)=>new StartTimesheetReviewCommand(o,x,a),ct);
 static async Task<IResult> Approve(Guid id,DecisionRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new ApproveTimesheetCommand(o,new TimesheetId(id),q.Reason,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Reject(Guid id,DecisionRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new RejectTimesheetCommand(o,new TimesheetId(id),q.Reason??string.Empty,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static Task<IResult> Lock(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct)=>Send(id,m,t,u,(o,x,a)=>new LockTimesheetCommand(o,x,a),ct);
 static async Task<IResult> Send<T>(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,Func<OrganizationId,TimesheetId,UserId,T> factory,CancellationToken ct) where T:DriveOS.Application.Abstractions.Messaging.ICommand{if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(factory(o,new TimesheetId(id),a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static IResult Problem(Error e)=>Results.Problem(statusCode:e.Type switch{ErrorType.NotFound=>404,ErrorType.Conflict=>409,ErrorType.Validation=>400,_=>400},extensions:new Dictionary<string,object?>{{"code",e.Code},{"messageKey",e.MessageKey}});
}
public sealed record CreateTimesheetRequest(Guid? Id,Guid EmployeeId,DateOnly PeriodFrom,DateOnly PeriodTo);
public sealed record TimesheetEntryRequest(Guid? Id,DateOnly Date,TimesheetActivityType ActivityType,decimal Hours,string? Description,TimesheetEntrySource Source,string? SourceReference);
public sealed record DecisionRequest(string? Reason);
