using DomainRelay.Abstractions; using DriveOS.Application.Abstractions.Authentication; using DriveOS.Modules.Workforce.Application.WorkingTime; using DriveOS.SharedKernel.Identifiers; using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.Workforce;
internal static class WorkingTimeEndpoints
{
 internal static IEndpointRouteBuilder MapWorkingTimeEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/workforce").WithTags("Workforce - Working Time");g.MapGet("/employees/{employeeId:guid}/working-time-policies",List).RequireAuthorization("Workforce.WorkingTime.Read");g.MapPost("/employees/{employeeId:guid}/working-time-policies",Create).RequireAuthorization("Workforce.WorkingTime.Manage");g.MapPut("/working-time-policies/{id:guid}",Update).RequireAuthorization("Workforce.WorkingTime.Manage");g.MapPost("/working-time-policies/{id:guid}/deactivate",Deactivate).RequireAuthorization("Workforce.WorkingTime.Manage");g.MapGet("/employees/{employeeId:guid}/working-time-summary",Summary).RequireAuthorization("Workforce.WorkingTime.Read");return app;}
 static async Task<IResult> List(Guid employeeId,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetWorkingTimePoliciesQuery(o,new EmployeeId(employeeId)),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static async Task<IResult> Create(Guid employeeId,WorkingTimePolicyRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var id=q.Id is{}x&&x!=Guid.Empty?new WorkingTimePolicyId(x):WorkingTimePolicyId.New();var r=await m.Send(new CreateWorkingTimePolicyCommand(o,id,new EmployeeId(employeeId),q.EffectiveFrom,q.EffectiveTo,q.ContractualWeeklyHours,q.ContractualDailyHours,q.MaxWorkingDaysPerWeek,a),ct);return r.IsSuccess?Results.Created($"/api/workforce/working-time-policies/{r.Value.Value}",new{id=r.Value.Value}):Problem(r.Error);}
 static async Task<IResult> Update(Guid id,WorkingTimePolicyRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new UpdateWorkingTimePolicyCommand(o,new WorkingTimePolicyId(id),q.EffectiveFrom,q.EffectiveTo,q.ContractualWeeklyHours,q.ContractualDailyHours,q.MaxWorkingDaysPerWeek,a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Deactivate(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(t.OrganizationId is not{}o||u.UserId is not{}a)return Results.Unauthorized();var r=await m.Send(new DeactivateWorkingTimePolicyCommand(o,new WorkingTimePolicyId(id),a),ct);return r.IsSuccess?Results.NoContent():Problem(r.Error);}
 static async Task<IResult> Summary(Guid employeeId,DateOnly from,DateOnly to,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not{}o)return Results.Unauthorized();var r=await m.Send(new GetWorkingTimeSummaryQuery(o,new EmployeeId(employeeId),from,to),ct);return r.IsSuccess?Results.Ok(r.Value):Problem(r.Error);}
 static IResult Problem(Error e)=>Results.Problem(statusCode:e.Type switch{ErrorType.NotFound=>404,ErrorType.Conflict=>409,ErrorType.Validation=>400,_=>400},extensions:new Dictionary<string,object?>{{"code",e.Code},{"messageKey",e.MessageKey}});
}
public sealed record WorkingTimePolicyRequest(Guid? Id,DateOnly EffectiveFrom,DateOnly? EffectiveTo,decimal ContractualWeeklyHours,decimal? ContractualDailyHours,int? MaxWorkingDaysPerWeek);
