using DomainRelay.Abstractions;
using DriveOS.Application.Abstractions.Authentication;
using DriveOS.Modules.CurriculumPedagogy.Application.Curricula;
using DriveOS.Modules.CurriculumPedagogy.Application.LicenseCategories;
using DriveOS.SharedKernel.Identifiers;using DriveOS.SharedKernel.Results;
namespace DriveOS.Api.Endpoints.CurriculumPedagogy;
public static class CurriculumEndpoints
{
 public static IEndpointRouteBuilder MapCurriculumPedagogyEndpoints(this IEndpointRouteBuilder e){var g=e.MapGroup("/api/pedagogy").WithTags("Curriculum & Pedagogy");g.MapGet("/license-categories",ListCategories).RequireAuthorization("Pedagogy.Curricula.Read");g.MapGet("/curricula",List).RequireAuthorization("Pedagogy.Curricula.Read");g.MapGet("/curricula/{id:guid}",Get).RequireAuthorization("Pedagogy.Curricula.Read");g.MapPost("/license-categories",CreateCategory).RequireAuthorization("Pedagogy.Curricula.Manage");g.MapPost("/license-categories/{id:guid}/activate",ActivateCategory).RequireAuthorization("Pedagogy.Curricula.Manage");g.MapPost("/curricula",Create).RequireAuthorization("Pedagogy.Curricula.Manage");g.MapPost("/curricula/{id:guid}/versions",CreateVersion).RequireAuthorization("Pedagogy.Curricula.Manage");g.MapPost("/curricula/{id:guid}/versions/{versionId:guid}/modules",AddModule).RequireAuthorization("Pedagogy.Curricula.Manage");g.MapPost("/curricula/{id:guid}/versions/{versionId:guid}/modules/{moduleId:guid}/competencies",AddCompetency).RequireAuthorization("Pedagogy.Curricula.Manage");g.MapPost("/curricula/{id:guid}/versions/{versionId:guid}/publish",Publish).RequireAuthorization("Pedagogy.Curricula.Publish");g.MapTrainingPathEndpoints();g.MapCompetencyAssessmentEndpoints();g.MapPedagogicalProgressionEndpoints();g.MapPedagogicalReviewEndpoints();g.MapRemediationPlanEndpoints();g.MapPedagogicalReadinessEndpoints();g.MapStudentPedagogyOverviewEndpoints();return e;}
 static bool Context(ICurrentTenant t,ICurrentUser u,out OrganizationId org,out UserId actor){org=t.OrganizationId??OrganizationId.Empty;actor=u.UserId??UserId.Empty;return !org.IsEmpty&&!actor.IsEmpty;}
 static IResult Fail(Error x)=>Results.Problem(statusCode:x.Type==ErrorType.NotFound?404:x.Type==ErrorType.Conflict?409:400,title:x.Code,detail:x.MessageKey);
 static async Task<IResult> ListCategories(ICurriculumReadService s,ICurrentTenant t,CancellationToken ct)
        =>t.OrganizationId is { } o?Results.Ok(await s.ListLicenseCategoriesAsync(o,ct)):Results.Unauthorized();
 static async Task<IResult> List(ICurriculumReadService s,ICurrentTenant t,CancellationToken ct)=>t.OrganizationId is { } o?Results.Ok(await s.ListAsync(o,ct)):Results.Unauthorized();
 static async Task<IResult> Get(Guid id,ICurriculumReadService s,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not { } o)return Results.Unauthorized();var x=await s.GetAsync(o,new CurriculumId(id),ct);return x is null?Results.NotFound():Results.Ok(x);}
 static async Task<IResult> Create(CreateCurriculumRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(!Context(t,u,out var o,out var a))return Results.Unauthorized();var r=await m.Send(new CreateCurriculumCommand(o,q.Code,q.Name,q.Description,q.CountryCode,q.LicenseCategoryCode,a),ct);return r.IsSuccess?Results.Created($"/api/pedagogy/curricula/{r.Value.Value}",new{id=r.Value.Value}):Fail(r.Error);}
 static async Task<IResult> CreateCategory(CreateLicenseCategoryRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(!Context(t,u,out var o,out var a))return Results.Unauthorized();var r=await m.Send(new CreateLicenseCategoryCommand(o,q.CountryCode,q.Code,q.Name,q.Description,a),ct);return r.IsSuccess?Results.Created($"/api/pedagogy/license-categories/{r.Value.Value}",new{id=r.Value.Value}):Fail(r.Error);}
 static async Task<IResult> ActivateCategory(Guid id,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(!Context(t,u,out var o,out var a))return Results.Unauthorized();var r=await m.Send(new ActivateLicenseCategoryCommand(o,new LicenseCategoryDefinitionId(id),a),ct);return r.IsSuccess?Results.NoContent():Fail(r.Error);}
 static async Task<IResult> CreateVersion(Guid id,CreateVersionRequest q,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(!Context(t,u,out var o,out var a))return Results.Unauthorized();var r=await m.Send(new CreateCurriculumVersionCommand(o,new CurriculumId(id),q.EffectiveFrom,q.EffectiveTo,q.ChangeSummary,a),ct);return r.IsSuccess?Results.Ok(new{id=r.Value.Value}):Fail(r.Error);}
 static async Task<IResult> AddModule(Guid id,Guid versionId,AddModuleRequest q,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not { } o)return Results.Unauthorized();var r=await m.Send(new AddCurriculumModuleCommand(o,new CurriculumId(id),new CurriculumVersionId(versionId),q.Code,q.Name,q.Description,q.Order),ct);return r.IsSuccess?Results.Ok(new{id=r.Value.Value}):Fail(r.Error);}
 static async Task<IResult> AddCompetency(Guid id,Guid versionId,Guid moduleId,AddCompetencyRequest q,IMediator m,ICurrentTenant t,CancellationToken ct){if(t.OrganizationId is not { } o)return Results.Unauthorized();var r=await m.Send(new AddCompetencyCommand(o,new CurriculumId(id),new CurriculumVersionId(versionId),new CurriculumModuleId(moduleId),q.Code,q.Name,q.Description,q.LearningObjective,q.Order,q.IsRequired),ct);return r.IsSuccess?Results.Ok(new{id=r.Value.Value}):Fail(r.Error);}
 static async Task<IResult> Publish(Guid id,Guid versionId,IMediator m,ICurrentTenant t,ICurrentUser u,CancellationToken ct){if(!Context(t,u,out var o,out var a))return Results.Unauthorized();var r=await m.Send(new PublishCurriculumVersionCommand(o,new CurriculumId(id),new CurriculumVersionId(versionId),a),ct);return r.IsSuccess?Results.NoContent():Fail(r.Error);}
}
public sealed record CreateCurriculumRequest(string Code,string Name,string? Description,string CountryCode,string LicenseCategoryCode);public sealed record CreateLicenseCategoryRequest(string CountryCode,string Code,string Name,string? Description);public sealed record CreateVersionRequest(DateOnly EffectiveFrom,DateOnly? EffectiveTo,string? ChangeSummary);public sealed record AddModuleRequest(string Code,string Name,string? Description,int Order);public sealed record AddCompetencyRequest(string Code,string Name,string? Description,string LearningObjective,int Order,bool IsRequired=true);
