using DriveOS.Modules.Workforce.Domain.ProfessionalRestrictions;using DriveOS.SharedKernel.Identifiers;using Microsoft.EntityFrameworkCore;
namespace DriveOS.Modules.Workforce.Infrastructure.Persistence.Repositories;
internal sealed class ProfessionalRestrictionRepository(WorkforceDbContext db):IProfessionalRestrictionRepository
{
 public Task<ProfessionalRestriction?> GetAsync(OrganizationId org,ProfessionalRestrictionId id,bool tracking,CancellationToken ct=default){IQueryable<ProfessionalRestriction> q=db.ProfessionalRestrictions;if(!tracking)q=q.AsNoTracking();return q.SingleOrDefaultAsync(x=>x.OrganizationId==org&&x.Id==id,ct);}
 public async Task<IReadOnlyList<ProfessionalRestriction>> ListAsync(OrganizationId org,EmployeeId? employeeId,ProfessionalRestrictionStatus? status,ProfessionalRestrictionActivity? activity,CancellationToken ct=default){var q=db.ProfessionalRestrictions.AsNoTracking().Where(x=>x.OrganizationId==org);if(employeeId.HasValue)q=q.Where(x=>x.EmployeeId==employeeId.Value);if(status.HasValue)q=q.Where(x=>x.Status==status.Value);if(activity.HasValue)q=q.Where(x=>x.Activity==activity.Value);return await q.OrderByDescending(x=>x.StartDate).ToListAsync(ct);}
 public Task<bool> HasOverlapAsync(OrganizationId org,EmployeeId employeeId,ProfessionalRestrictionActivity activity,DateOnly from,DateOnly? to,string? countryCode,string? licenseCategoryCode,BranchId? branchId,ProfessionalRestrictionId? excluding,CancellationToken ct=default){var max=to??DateOnly.MaxValue;countryCode=N(countryCode);licenseCategoryCode=N(licenseCategoryCode);return db.ProfessionalRestrictions.AsNoTracking().AnyAsync(x=>x.OrganizationId==org&&x.EmployeeId==employeeId&&x.Activity==activity&&x.Status!=ProfessionalRestrictionStatus.Lifted&&x.Status!=ProfessionalRestrictionStatus.Cancelled&&(!excluding.HasValue||x.Id!=excluding.Value)&&x.StartDate<=max&&(!x.EndDate.HasValue||x.EndDate.Value>=from)&&x.CountryCode==countryCode&&x.LicenseCategoryCode==licenseCategoryCode&&x.BranchId==branchId,ct);}
 public void Add(ProfessionalRestriction x)=>db.ProfessionalRestrictions.Add(x);private static string? N(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim().ToUpperInvariant();
}
